README.md

Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

Correcting the indentation of the README

---

.github/workflows/security.yml

CI security scan using GHA and Snyk

CI security scan

---

.github/workflows/test.yml
Dockerfile
scripts/infra_build.mk

* Added a Windows build job to the test GitHub Actions.
* Added missing Makefile target used for building Linux binaries
* Added `jq` and `tree` to our build Dockerfile as useful for debugging

ci: added build job for Windows

---

pkg/metrics/storage/storage_sampler.go
pkg/metrics/storage/storage_sampler_test.go
test/harvest/storage_sampler_linux_test.go

ReadWriteBytesPerSecond as a sum of ReadBytesPerSec and WriteBytesPerSec metrics
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

Add a new metric ReadWriteBytesPerSecond for the storage sampler

---

internal/agent/service/job_windows.go
internal/agent/service/service_windows.go
win_build.ps1

* Added Windows Job Object to handle the child processes when agent
process exits.

Handle Agent Child processes on windows

---

pkg/config/defaults.go
test/core/deltas_test.go
test/core/large_string_metrics_test.go
test/fixture/integration/protocol_v4.go
test/fixture/inventory/assert.go
test/fuzz/integration_payload/corpus/v4Payload.json
test/harvest/custom_attributes_test.go
test/harvest/processmetrics_test.go
test/harvest/storage_sampler_linux_test.go
test/infra/http/http.go

Fixing and making sure that harvest test can run correctly.
Have removed from [storage_sampler_linux_test.go](test/harvest/storage_sampler_linux_test.go) the failing assert and will raise and issue to come back to look at why it fails on some OSs.

Fixing harvest tests

---

internal/agent/agent.go
internal/agent/agent_test.go
pkg/config/config.go

Added configuration option to enable/disable all process sampling reporting

feat: enable/disable process sample reporting via config

---

README.md

README update for OS/arch targets

README update for OS/arch targets

---

internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/delta/last_submission.go
internal/agent/delta/last_submission_inmemory.go
internal/agent/delta/store.go
internal/agent/delta/store_test.go
internal/agent/patch_sender.go
internal/agent/patch_sender_test.go
pkg/config/config.go
test/infra/agent.go

Refactor:
- Simplification on legacy inventory spaghetti conditions for inventory full submission.
- Usage of patch-sender constructor on tests
- Extract last-submission-store from delta-store

Inventory full submission simplification

---

.github/workflows/security.yml
.github/workflows/test.yml

CI not only for master branch

---

build/container/Dockerfile
build/container/Makefile

This fixes the issue #38 as I've upgraded the base image to Alpine 3.12 and update `curl` to version `7.69.1-r0`.

chore: updated agent base image to Alpine 3.12

---

pkg/metrics/sampler/matcher.go
pkg/metrics/sampler/matcher_test.go

…cess filter config
This PR will handle the situation when an invalid regex is provided for process filtering in the configuration file.

Fix panic caused by providing a not valid regex pattern

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/troubleshooting.md
README.md

Updated:
- updated README.md with updated Privacy and Contributing text 
Added:
- added feature_request.md file
- added troubleshooting.md file

Added missing docs

---

pkg/databind/internal/discovery/docker/docker.go

This PR will close docker client connection from discovery to avoid leaking file descriptors.
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

Fix defer closing docker client connection

---

go.mod
go.sum
internal/agent/delta/store_test.go
internal/agent/service/service_windows.go
internal/feature_flags/feature_flags.go
pkg/ctl/notification_handler_windows.go
pkg/ctl/sender/client_windows.go
pkg/ctl/sender/client_windows_test.go
pkg/helpers/windows/notification.go

Fixing certain tests that fail/complain when running on Windows.

fix: Windows pipe issues in tests

---

README.md
docs/README.md
docs/hostname_resolution.md

Extending documentation on architecture, runtime and components.

Extended documentation

---

.github/workflows/test.yml
Makefile
build/container/Dockerfile
build/container/Makefile
build/embed_ohis.mk
build/nri-integrations

Add missing Makefiles used to build the [`newrelic/infrastructure`](https://hub.docker.com/r/newrelic/infrastructure) Docker image.

feat: Added makefiles used to build Docker containers of the agent

---

internal/agent/delta/last_entityId.go
internal/agent/delta/last_entityId_test.go

Missing copyrights

---

go.mod

Fix vendor indirect dependency

Fix vendor dependency direct type

---

build/container/Makefile

Added missing make targets for container build.

feat: added Make targets for forwarder containers

---

build/nri-integrations

Update nri-docker to 1.3.2
- [x ] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
- [x ] clean and format the code
- [x ] add unit tests for your changes and make sure all unit tests are passing
- [x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x ] address the feedback

[needs nri-docker release] Update nri-docker to 1.3.2

---

cmd/newrelic-infra/newrelic-infra.go
pkg/backend/identityapi/register_client.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go
pkg/integrations/v4/dm/id_provider.go
pkg/integrations/v4/dm/id_provider_test.go

Add id_provider for entity registration, this id_provider also contains lookup cache storage.

feat: register entities - id lookup

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_template.go
pkg/integrations/v4/logs/cfg_test.go

We need to add a new FB filter for winlog (Modify filter) Is a small change part of MMF LOGGING-2816
More info https://newrelic.atlassian.net/browse/LOGGING-3157

[LOGGING-3157] modify Message and EventType

---

cmd/newrelic-infra/newrelic-infra.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go
pkg/integrations/v4/dm/id_provider.go
pkg/integrations/v4/dm/id_provider_test.go

Async entity registration for DM

feat: add async flow for v4/dm/id_provider.go

---

pkg/integrations/v4/sequence.plantuml

"Simplified" integrations v4 DM sequence diagram with current entity registration with current async https://github.com/newrelic/infrastructure-agent/pull/79 .

Integration protocol v4, DM sequence diagram

---

internal/agent/delta/store.go

fixes https://github.com/newrelic/infrastructure-agent/issues/101

fix(agent): fixes panic when compacting storage

---

internal/integrations/v4/integration/definition_test.go
internal/integrations/v4/integration/integration.go
internal/integrations/v4/integration/integration_test.go
internal/integrations/v4/runner/runner_load.go
internal/integrations/v4/runner/runner_test.go

Simply renaming things for readability

refactor: integrations v4 naming

---

pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_bench_test.go
pkg/integrations/v4/dm/emitter_test.go
pkg/integrations/v4/emitter/emitter.go
pkg/integrations/v4/emitter/emitter_test.go

Also refactor `Send()` calls to use a DTO aimed to be enqueued in next PR.

Remove register 2nd call

---

assets/examples/logging/windows/winlog.yml.example
build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs.template
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs.template

We added the missing config example file for Windows log events

feat: add winlog example config file

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_test.go
pkg/integrations/v4/logs/loader_test.go

This PR is about removing unused code regarding to EventLog (first iteration of winlog)

refactor: remove unused code (eventlog)

---

build/infra_build.mk
cmd/newrelic-infra/newrelic-infra.go
internal/agent/cmdchannel/cmdchannel.go
internal/agent/cmdchannel/handler/featureflag_handler.go
internal/agent/cmdchannel/service.go
internal/agent/cmdchannel/service_test.go
internal/integrations/v4/runner/group.go
internal/integrations/v4/runner/group_load.go
internal/integrations/v4/runner/group_test.go
internal/integrations/v4/runner/runner.go
internal/integrations/v4/runner/runner_test.go
internal/integrations/v4/testhelp/testemit/testemit.go
pkg/integrations/cmdrequest/handler.go
pkg/integrations/cmdrequest/protocol/jsonlines_test.go
pkg/integrations/v4/fixtures/cmdreq/cmdreq.go
pkg/integrations/v4/fixtures/cmdreq/v4.sh
pkg/integrations/v4/fixtures/fixtures.go
pkg/integrations/v4/manager.go
pkg/integrations/v4/manager_test.go
pkg/integrations/v4/sequence.plantuml
pkg/trace/features.go

Replaces https://github.com/newrelic/infrastructure-agent/pull/151 so branch can be imported.
See: https://github.com/golang/go/issues/38861

Cmdrequest handler

---

pkg/metrics/storage/storage_sampler.go
pkg/metrics/storage/storage_sampler_linux.go

Some readability boyscout while going through the storage codebase.

refactor: storage readability

---

pkg/integrations/v4/dm/sender_test.go
pkg/integrations/v4/dm/telemetry.go

Prometheus summary type calculate delta value to properly allow average calculation in NRQL.
Fixes #188

fix: calculate delta prometheus summary

---

cmd/newrelic-infra/newrelic-infra.go

Increases log severity level from Debug to Waarning and adds error message to entry context.

feat: increaed severity & contextulised connectivity check error

---

pkg/integrations/legacy/runner.go
pkg/metrics/storage/storage_sampler.go
pkg/metrics/storage/storage_sampler_linux.go

Reverts newrelic/infrastructure-agent#218

Revert "chore: remove dead code"

---

internal/agent/patch_reaper.go
pkg/integrations/v4/protocol/types_test.go

Simply testing that integrations are able to override default category.

test: event category override

---

cmd/newrelic-infra/newrelic-infra.go
internal/integrations/v4/runner/group.go
internal/integrations/v4/runner/group_load.go
internal/integrations/v4/runner/group_test.go
internal/integrations/v4/runner/runner.go
pkg/config/config.go
pkg/databind/pkg/databind/binder.go
pkg/databind/pkg/databind/config.go
pkg/integrations/legacy/registry.go
pkg/integrations/legacy/registry_test.go
test/proxy/minagent/main-agent/agentmain.go

Some boy-scouting for databind.
Just refactoring, nothing should change.

Databind boy-scout

---

pkg/entity/register/worker.go
pkg/entity/register/worker_test.go
pkg/integrations/v4/dm/emitter_test.go

Fix when submitted entity payload exceed limits in byte size and batch size.

fix: register when check batch size in bytes to accumulate

---

internal/agent/delta/store.go
internal/agent/delta/store_test.go

This is just a simple clean up of `store_test.go` to remove the test suite.

style: Removed test suite from store_test.go

---

internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/runintegration/runintegration_test.go
internal/agent/cmdchannel/service/service_test.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
internal/agent/cmdchannel/stopintegration/stopintegration_test.go
pkg/integrations/cmdapi/cmdapi.go
pkg/integrations/cmdapi/cmdapi_test.go

Fixes wrong allowed integration name and condition

fix: cmd API allow list

---

build/.goreleaser.yml

Remove pinned release from packages homepage

fix packages homepage

---

.github/workflows/security.yml
README.md
build/ci.mk
build/container/Dockerfile

This PR also fixes Snyk not running correctly and building the Docker image of the agent.

doc: Updated README.md with missing build badge

---

build/container/Makefile

Fixes docker buildx conditionals. Details at https://github.com/newrelic/infrastructure-agent/runs/2015220196?check_suite_focus=true

fix: docker build conditionals

---

test/manual/use-case/zypper_validations.dm

In this PR You can will find steps instructions to validate agent system acceptance tests.
* Zypper validations for each scenario.

test: system acceptance test zypper validation

---

test/manual/use-case/docker_validations.md

In this PR You can will find steps instructions to validate agent system acceptance tests.
* Docker validations for each scenario.

test: system acceptance test docker validation

---

build/container/Dockerfile

Reverts newrelic/infrastructure-agent#387

Revert "container/k8s-events-forwarder: set ConnectEnabled to false"

---

test/packaging/ansible/roles/package-files-verification/tasks/main.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Amazon-2-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-7-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-7.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-8-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-8.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-SLES-12.3.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-16-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-16.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-18-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-18.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-20-aarch64.yaml
test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-20.yaml
test/packaging/ansible/test.yml

Verify that expected files installed from the package are present after installation.
Configurable by distribution/architecture.

test: packaging files presence verification

---

test/packaging/ansible/roles/initial-install/tasks/main.yaml
test/packaging/ansible/roles/initial-install/tasks/repo-CentOS.yaml
test/packaging/ansible/roles/initial-install/tasks/repo-RedHat.yaml

Fix: installation test for Amazon Linux 2

fix install test amz linux 2

---

test/packaging/ansible/clear-package-manager-cache.yml
test/packaging/ansible/repo-setup.yml
test/packaging/ansible/roles/agent-install/tasks/main.yml
test/packaging/ansible/test.yml

- setup repo at test suite init
- clean repo cache

fix: repo setup

---

test/packaging/ansible/installation-unprivileged.yml
test/packaging/ansible/roles/cleanup/tasks/service-Linux.yaml
test/packaging/ansible/roles/repo-setup/tasks/main.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Amazon.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-CentOS.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-RedHat.yaml

- fix: repo setup for unpriv
- feat: ignore false errors
- fix: AL2 repo
- feat: yum clean without warns

fix install test al2

---

build/container/Dockerfile

https://pkgs.alpinelinux.org/packages?name=curl&branch=v3.13

chore: bump Alpine curl

---

.github/workflows/prerelease_linux.yml
build/embed/fluent-bit.version

* fix: type in publish action version
* fix: don't remove windows fb binary version

fix: fixed typo in prerelease publish action tag

---

build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs
build/package/windows/newrelic-infra-386-installer/newrelic-infra/newrelic-infra-installer.wixproj
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/newrelic-infra-installer.wixproj
internal/agent/service/service.go

This PR will add recovery policy for the Windows service:
On service fail action: restart service
Restart after: 30 seconds

feat: added recovery policy for windows service

---

cmd/newrelic-infra/newrelic-infra.go
pkg/backend/telemetryapi/config.go
pkg/backend/telemetryapi/config_test.go
pkg/integrations/v4/dm/sender.go
pkg/integrations/v4/dm/telemetry.go
test/cfgprotocol/agent/emulator.go

Fixes https://github.com/newrelic/infrastructure-agent/issues/529
Source https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints/#trace-api

fix: fedramp endpoint for spans

---

build/.goreleaser.yml

This PR will add darwin build steps for all three binaries of newrelic-infra agent

feat: added build for darwin in goreleaser

---

build/.goreleaser.yml
build/fix_darwin_tarballs.sh
build/release.mk

This PR adds script for building the tarball for darwin builds

feat: added tarball for darwin build

---

.github/workflows/prerelease_macos.yml
.github/workflows/prerelease_staged_publish.yml
.github/workflows/release_staged.yml
.github/workflows/test.yml
test/harvest/ansible/roles/build-harvest-tests/vars/main.yml

This runs MacOS harvest test suite on PRs and pre-release workflows, as done for Linux.

MacOS harvest test suite on PR and pre-release

---

build/embed/fluent-bit.version

Update the infra-agent in order to get the latest Fluent-bit version `1.7.9`

Upgrade fluent-bit version to 1.7.9

---

.github/workflows/prerelease_macos.yml
.github/workflows/prerelease_staged_publish.yml

- fix: macOS release GPG
- fix: macOS manual prerelease OS input

Fix macOS release GPG

---

docs/status_api.md
internal/agent/status/status.go
internal/agent/status/status_test.go
internal/httpapi/httpapi.go
internal/httpapi/httpapi_test.go

- docs: entity status API spec
- feat: entity status API implementation

Entity status API

---

internal/agent/agent.go
pkg/integrations/v4/emitter/emitter_test.go

- Log truncated or dropped events as warnings
- Log discarded events by matching rules in debug (will only show up in verbose mode)
- Test integration protocol v2 from nri-ecs

Log truncated or dropped events + test integration protocol v2 from nri-ecs

---

build/embed/integrations.version

https://github.com/newrelic/nri-flex/releases/tag/v1.4.3

chore: bump flex

---

build/package/launchd/Library/LaunchDaemons/com.newrelic.infrastructure.plist
pkg/config/config_darwin.go

- feat: default OSX config paths
- feat: OSX launchd service plist file

Launchd plist

---

.github/workflows/prerelease_linux.yml
.github/workflows/prerelease_macos.yml
.github/workflows/prerelease_staged_publish.yml
.github/workflows/release.yml
.github/workflows/release_staged.yml

Latest version of the publish-action has a fix to release packages for new OS versions.

chore: update publish action to v1.0.19

---

build/.goreleaser_linux.yml
build/embed/fluent-bit.version

In this PR I include fluent bit as a recommended package for SLES12.5.

feat: add fluent bit as recommended package for SLES12.5

---

assets/examples/infrastructure/newrelic-infra-template.yml.example

the trace feature introduced by PR#589 has included an incorrect example YAML

fix trace example YAML

---

tools/spin-ec2/ansible.go
tools/spin-ec2/config.go
tools/spin-ec2/main.go

fix: provision canaries by OS

---

test/synthetic/latest_release_cdn.js

Follow-up from #791 with signed commits. 
Adding JS NR synthetic custom script to validate latest release packages available in CDN (download server).

test: synthetics js script for cdn check (signed)

---

tools/provision-alerts/README.md
tools/provision-alerts/alerts.mk
tools/provision-alerts/config/config.go
tools/provision-alerts/main.go
tools/provision-alerts/service/service.go
tools/provision-alerts/service/service_mock.go
tools/provision-alerts/service/service_test.go
tools/provision-alerts/template/template-adjusted.yml
tools/spin-ec2/config.go
tools/spin-ec2/main.go
tools/spin-ec2/spin-ec2.mk

* thresholds for canaries divided in long running (template.yml) and spawned at the same time (template-adjusted.yml)
* added option to delete created alerts by prefix
* added prefix by parameter

adjust canaries alerts thresholds

---

test/packaging/ansible/README.md
test/packaging/ansible/roles/agent-restart/tasks/agent-restart-Win32NT.yaml
test/packaging/ansible/roles/agent-stop/tasks/main.yml
test/packaging/ansible/roles/agent-stop/tasks/stop-Linux.yaml
test/packaging/ansible/roles/agent-stop/tasks/stop-Win32NT.yaml
test/packaging/ansible/roles/ec2-start/tasks/main.yml
test/packaging/ansible/roles/ec2-stop/tasks/main.yml
test/packaging/ansible/roles/ec2-terminate/tasks/main.yml
test/packaging/ansible/roles/infrastructure-alert-create/defaults/main.yml
test/packaging/ansible/roles/infrastructure-alert-create/tasks/main.yml
test/packaging/ansible/roles/infrastructure-alert-delete/defaults/main.yml
test/packaging/ansible/roles/infrastructure-alert-delete/tasks/main.yml
test/packaging/ansible/roles/infrastructure-alert-violation-assert/defaults/main.yml
test/packaging/ansible/roles/infrastructure-alert-violation-assert/tasks/main.yml
test/packaging/ansible/shutdown.yml
test/packaging/ansible/test.yml

* Install agent
* Create HNR alert
* stop the agent -> (wait) -> verify alert is opened
* start the agent -> (wait) ->verify alert is closed 
* shutdown the host -> (wait) -> verify alert is **not** opened 
* start the host
* terminate the host -> (wait) -> verify alert is **not** opened 
* delete alert

test: automated test for agent shutdown and HNR alert

---

.github/workflows/prerelease_linux.yml
.github/workflows/prerelease_macos.yml
.github/workflows/prerelease_staged_publish.yml
.github/workflows/prerelease_windows.yml
.github/workflows/release.yml
.github/workflows/release_staged.yml

chore: update infrastructure-publish-action

---

test/packaging/ansible/roles/agent-upgrade/tasks/upgrade-Debian.yaml
test/packaging/ansible/roles/agent-upgrade/tasks/upgrade-RedHat.yaml
test/packaging/ansible/roles/nri-docker/tasks/install-docker-Centos.yaml
test/packaging/ansible/roles/package-install-pinned/tasks/package-Debian.yaml
test/packaging/ansible/roles/package-install/tasks/package-Debian.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Ubuntu.yaml

Small tweaks to fix non working packaging errors

test: fix packaging tests errors

---

.github/workflows/prerelease_linux.yml
.github/workflows/prerelease_macos.yml
.github/workflows/prerelease_staged_publish.yml
.github/workflows/prerelease_windows.yml
.github/workflows/release.yml
.github/workflows/release_staged.yml
build/ci.mk

* add iptables rule to avoid network errors in pipeline when releasing the packages
* update publish action to avoid network errors in pipeline when publishing the packages [NOT MERGED YET]

ci: avoid network errors uploading assets to GH and publishing to packages 

---

internal/agent/agent.go
internal/agent/cmdchannel/fflag/ffhandler.go
internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/service/service.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
internal/agent/connect_service.go
internal/agent/delta/store.go
pkg/integrations/cmdrequest/handler.go
pkg/integrations/v4/dm/telemetry.go
pkg/integrations/v4/supervisor.go
pkg/log/log.go
pkg/metrics/disk_linux.go
pkg/metrics/process/harvester_linux.go
pkg/metrics/sampler/matcher.go
pkg/plugins/custom_attrs.go
pkg/sysinfo/hostname/hostname.go
pkg/sysinfo/hostname/hostname_darwin.go
pkg/sysinfo/hostname/hostname_lin_win.go
pkg/trace/features.go
pkg/trace/trace.go
pkg/trace/trace_test.go

Add logrus.Fields to feature traces, thus we could filter on even more fields. For example, the "structure", "integration_name", "plugin", etc

feat: add logrus.Fields to feature trace output

---

internal/integrations/v4/runner/runner.go

feat: add integrations payload to self instrumentation

---

pkg/helpers/helpers.go
pkg/metrics/cpu.go
pkg/metrics/network/network_unix.go
pkg/metrics/network/network_windows.go
pkg/metrics/storage/storage_sampler.go
pkg/metrics/system_sampler.go
pkg/trace/features.go

Check the traced messages with the following config:
```yaml
verbose: 3
trace:
- "sampler"
```
And grep by "feature="

Logging improvements/add samplers feature trace

---

.github/workflows/component_molecule_packaging.yml
.github/workflows/molecule_packaging_tag.yml
.github/workflows/prerelease_linux.yml
.github/workflows/release.yml
.github/workflows/test.yml
test/packaging/ansible/molecule/default/Dockerfile.al2022
test/packaging/ansible/molecule/default/Dockerfile.centos8
test/packaging/ansible/molecule/default/Dockerfile.ub1804
test/packaging/ansible/molecule/default/converge.yml
test/packaging/ansible/molecule/default/molecule.yml
test/packaging/ansible/roles/repo-setup/tasks/repo-Ubuntu.yaml

Check if a given version of the infra-agent can be installed correctly on:
- Ubuntu 18
- Amazon Linux 2022
- Centos 8
It adds an additional layer of testing after any pre/release

[ID] Molecule packaging

---

cmd/newrelic-infra/newrelic-infra.go
pkg/config/config.go
pkg/config/config_test.go
pkg/log/exported.go
pkg/log/format/fields.go
pkg/log/format/fields_test.go

Adds a new configuration option for logging to filter by fields. It
also includes a logrus.Formatter implementation that performs this filtering.

feat: add logging filter configuration option

---

test/packaging/ansible/roles/ec2-terminate/tasks/main.yml
test/packaging/ansible/roles/infrastructure-alert-create/tasks/main.yml
test/packaging/ansible/shutdown-and-terminate.yml

This PR will fix the installation tests issue caused by the fact that we did handled correctly supported/unsupported OSs for Smart HNR
Also cleans up alert conditions even if the job fails (before we did the cleanup at the beginning of the job

fixed installation tests

---

.snyk

This PR ignore false positive CVE

added snyk ignore rules for false positive alerts

---

.github/renovate.json5

Based on: https://github.com/newrelic/infrastructure-bundle/pull/200

renovate: add dependencies label

---

build/upload_artifacts_gh.sh
build/windows/package_zip.ps1

Commits with the "delete me" title will be removed before merging.

Signing process for zip archives on Windows

---

pkg/log/rotate.go
pkg/log/rotate_test.go

This PR adds file rotation for logs

added file rotation

---

go.sum
pkg/log/rotate.go
pkg/log/rotate_test.go

This PR will purge older rotated log files if MaxFiles in config is exceeded.

feat: added purge functionality for older rotated files

---

.github/actions/external_runner/main.go

I was unable to parse arguments in a script while using this action.
I modified the entrypoint to something like this for debugging porpuses:
```shell
#!/usr/bin/env sh
set -e
set -x
echo "Called with these arguments: $*";
echo "Argument 1: $1";
echo "Argument 2: $2";
echo "Argument 3: $3";
while true; do
case "$1" in
-v | --verbose ) set -x; echo "Called with these arguments: $*"; shift ;;
-g | --repository ) REPO="$2"; shift 2 ;;
-r | --ref | --commit ) REF="$2"; shift 2 ;;
-h | --help ) help ;;
-- ) shift; break ;;
* ) break ;;
esac
done
```
So, now in the logs I was able to see why the argument parser was not working:
```
2022/08/16 10:42:33 Waiting for task to run...
2022/08/16 10:43:46 Task is running!
+ echo 'Called with these arguments: --verbose --repository …
```

[actions][external runner] Change command to a string slice

---

internal/agent/agent.go
internal/agent/cmdchannel/fflag/ffhandler.go
internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/service/service.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
internal/agent/connect_service.go
internal/agent/event_sender.go
pkg/config/config.go
pkg/config/config_test.go
pkg/helpers/helpers.go
pkg/integrations/cmdrequest/handler.go
pkg/integrations/v4/dm/telemetry.go
pkg/metrics/process/harvester_linux.go
pkg/metrics/sampler/matcher.go
pkg/plugins/custom_attrs.go
pkg/sysinfo/hostname/hostname.go
pkg/sysinfo/hostname/hostname_darwin.go
pkg/sysinfo/hostname/hostname_lin_win.go

From: https://github.com/newrelic/infrastructure-agent/pull/1186/files

NEWRELIC-3694 refactor: exclude feature traces log entries

---

assets/examples/infrastructure/newrelic-infra-template.yml.example

Added logging_retry_limit to the sample file.

Updated sample file

---

pkg/backend/telemetryapi/harvester.go
pkg/http/http_tracer.go

```
time="2022-11-25T12:22:30+01:00" level=debug action=TLSHandshakeStart component=HttpTracer requester=checkEndpointReachable
time="2022-11-25T12:22:30+01:00" level=debug action=TLSHandshakeDone component=HttpTracer duration=43ms requester=checkEndpointReachable version=1.3
```

log tls version in trace mode

---

pkg/log/rotate.go
pkg/log/rotate_test.go
pkg/log/rotate_unix.go
pkg/log/rotate_windows.go

This PR will add zip compression on Windows for infra-agent.log rotation

added log rotate zip compression for windows

---

.github/workflows/release.yml

As we agreed, let's maintain the canary alerts

ci: do not delete canary alerts on release

---

.github/workflows/component_canaries.yml
.github/workflows/component_canaries_prune.yml
.github/workflows/component_canary_alerts.yml
.github/workflows/component_canary_alerts_delete.yml
.github/workflows/component_prerelease_testing.yml
test/automated/terraform/fargate/main.tf
test/automated/terraform/fargate/vars.tf

- Once fully tested in the next prerelease, we can create a new PR to remove current infrastructure.
- Testing: https://github.com/newrelic/infrastructure-agent/actions/runs/4161972749

NR-81894: Update infra to use Infra Terraform module

---

build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs

This PR will create New Relic app data directory in c:\ProgramData with the specified permissions

Prepare data directory in windows during msi install

---

pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go

Change the default behavior when protocol_v4_enabled FF does not exist

NR-91503 feat: protocol_v4_enabled FF enabled by default

---

pkg/integrations/v4/supervisor_fb.go
pkg/integrations/v4/supervisor_fb_test.go

This reverts commit 531ac5dd75a604c97c65fb79802d8437adcf2867.

Revert "NR-72398 - Do not let Infra Agent's Fluent Bit config files fill up the disk (#1570)"

---

pkg/integrations/v4/supervisor_fb.go
pkg/integrations/v4/supervisor_fb_test.go

This is a C&P of https://github.com/newrelic/infrastructure-agent/pull/1570 after having added agent tmp folder

NR-72398 feat: Do not let Infra Agent's Fluent Bit config files fill the disk

---

test/automated/ansible/roles/remove-eol-sources/tasks/main.yml

Unable to sync with vault mirrors: https://serverfault.com/questions/1093922/failing-to-run-yum-update-in-centos-8

fix: replace centos vault repository

---

internal/agent/agent.go
internal/agent/cmdchannel/fflag/ffhandler.go
pkg/config/config.go

This PR adds handler for inventory_send_bulk_enabled ff

NR-95226 added ff for bulk inventory

---

build/embed/integrations.version

Bump nri-winservices to v1.0.1

Bump nri-winservices to v1.0.1

---

pkg/config/config.go
pkg/metrics/procs_windows.go
pkg/metrics/procs_windows_test.go

The new WMI implementation is able to override limitations that we have with our current process monitoring implementation when the agent is run as non-admin or any restricted environment. The new implementation kicks in if the 'enable_wmi_proc_data' flag is enabled.

NEWRELIC-7908 - Windows Process Monitoring Improvement 

---

build/embed/integrations.version

Update nri-prometheus to v2.18.4

Update nri-prometheus to v2.18.4

---

build/package/binaries/linux/installer.sh

Fix to stop setcap changes from being reset.

NR-141109 Infra agent executable privileges being reset fix

---

.github/workflows/security.yml
pkg/metrics/process/harvester_darwin_test.go
pkg/metrics/process/snapshot_darwin.go
pkg/metrics/process/snapshot_darwin_test.go

Compute the CmdLine on processes for darwin.
Add similiar logic to other OSs

Add cmdline process darwin (NR-155368)

---

test/packaging/ansible/agent-upgrade.yml
test/packaging/ansible/roles/assert-version/vars/main.yaml

the pinned install version needs to support debian 12

ci: bump pinned installation versions

---

internal/integrations/v4/integration/integration_test.go

This PR adds a test for integration interval config

test: integration interval from config

---

.github/workflows/component_linux_harvest_test.yml
.github/workflows/component_linux_unit_test.yml
cmd/newrelic-infra/newrelic-infra.go
pkg/log/rotate.go

from o666 to o600, only owner read/write permissions

NR-175301: create log files with reduced permissions

---

internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/connect_service.go
internal/agent/connect_service_test.go
pkg/backend/identityapi/connect_client.go
pkg/backend/identityapi/connect_client_test.go
pkg/backend/identityapi/metadata.go
pkg/backend/identityapi/metadata_mock.go
pkg/backend/identityapi/metadata_test.go
test/infra/agent.go
test/log/log_helper.go

This PR adds the environment variable NR_HOST_ID to the Entity Metadata sent by Connect if present.

NR-250191 feat: add host.id to connect metadata

---

test/harvest/hostmetrics_linux_test.go

The order of Harvest Host Tests is changed because the Cached files test alters the state for the following HostDisk test on Centos Stream.

Modify order Harvest Host Tests to not collision cached files

---

.github/workflows/security.yml

Execute security tests with the image created from the code in the PR

test the image from the current commit

---

.github/workflows/component_trivy.yml

Tag input is not read:
https://github.com/newrelic/infrastructure-agent/actions/runs/9893255675/job/27362482265

ci: fix trivy job

---

build/build.mk
test/databind/compose.go
test/proxy/README.md

fix test using deprecated docker-compose

chore: replace docker-compose -> docker compose

---

test/packaging/ansible/agent-upgrade.yml

Bump the upgrade scenario agent version so the latest SLES distro passes the pkg tests.

increase upgrade scenario for latest distros

---

build/embed/fluent-bit.version

Upgrade fluent bit version to 3.1.9

Upgrade fluent bit version to 3.1.9

---

test/packaging/ansible/installation-pinned.yml
test/provision/terraform/install-requirements.yml

chore: add suse repos

---

.github/CODEOWNERS

update codeowners to be ohai

---

.github/workflows/component_docker_packaging.yml
.github/workflows/component_docker_publish.yml
.github/workflows/component_trivy.yml
.github/workflows/prerelease_linux.yml
build/ci.mk
build/container/Dockerfile
build/container/Makefile
build/release.mk

Create new docker FIPS images

---

.github/workflows/component_docker_publish.yml

Fix docker publishing pipeline

Fix publishing of docker images

---

.github/workflows/recover_s3_repository_periodic_test.yml

This PR adds a recurrent job to test the disaster recovery procedure:
* It will create a perpetual file
* get the current time + sleep
* It will create a file (so this one gets deleted when we go back in time)
* ensure that the recovered folder/file is what we expect

ci: disaster recovery dry run action

---

test/canaries/deploy_canaries.yml
test/packaging/ansible/agent-upgrade.yml
test/packaging/ansible/installation-pinned.yml
test/packaging/ansible/test.yml

Tested with: https://github.com/newrelic/infrastructure-agent/actions/runs/13459346833

ci: update pinned version installation test for fips

---

build/embed/fluent-bit.version

Raised PR behalf of @AkhilReddyS-NR to run workflows and test cases.

Bump fluent bit version to 3.2.10

---

build/Dockerfile
internal/agent/delta/last_entityId_test.go
pkg/disk/disk_windows.go
pkg/entity/register/worker.go
pkg/helpers/fingerprint/fingerprint_test.go

- Fix lint errors
- ignore wrapcheck

NR-405078 fix lint errors

---

.github/workflows/component_linux_harvest_test.yml
build/Dockerfile
go.mod
test/canaries/deploy_macos_canaries.yml
test/databind/fargate/Dockerfile_test
test/proxy/Dockerfile_agent
test/proxy/Dockerfile_collector
tools/cdn-purge/go.mod
tools/spin-ec2/go.mod
tools/yamlgen/go.mod

- Downgrade go version from 1.24 to 1.23.8

NR-405078 : Downgrade go version to 1.23.8

---

internal/plugins/linux/sysvinit.go

Change log level to **Debug** so the standard log file is not filled along with the syslog file

chore: Update log level

---

test/a2q/containerSampleTests.yml

test: add container sample tests

---

.github/workflows/component_canaries.yml
.github/workflows/component_canaries_prune.yml
test/canaries/Makefile
test/canaries/deploy_a2q_canaries.yml

Updated logic to create install infra agent from 2 different account.

ci: condition to add windows canaries to different accounts

---

pkg/metrics/storage/storage_sampler_linux.go
pkg/metrics/storage/storage_sampler_linux_test.go

Reverts newrelic/infrastructure-agent#2069

Revert "feat: support aws efs mounts in storage samples"

---

build/embed/integrations.version

Upgraded embedded integration versions to fix high and critical vulns

chore: upgraded embedded integration versions

---

go.mod
go.sum
pkg/databind/internal/discovery/docker/docker.go
pkg/databind/internal/discovery/docker/docker_test.go

deps: upgrade docker api lib from v26 to v28
