newrelic/infrastructure-agent

.github/workflows/test.yml
scripts/infra_build.mk

This PR enables running Infra agent test on Go 1.9 so we can check that we are still able to support older Linux OS such as CentOS 5.

ci: Enabling job to run tests on Go 1.9

---

pkg/metrics/storage/storage_sampler_linux.go

CalculateDeviceMappings was returning early when it matched an lvm device and so it would not return all lvm matching devices and therefore not fetch IO disk counters for those devices

fix: do not return early when mapping devices

---

internal/agent/delta/store.go
pkg/sysinfo/cloud/cloud.go
pkg/sysinfo/cloud/cloud_test.go
scripts/infra_build.mk

The locking of some of the resources in [`cloud.go`](../tree/master/pkg/sysinfo/cloud/cloud.go ) would cause cloud metadata to not return data sometimes.
Also update the test target in the Makefile to timeout the tests after ten minutes. This should fix issue where tests would fail on slower machines.

Fixed issue where getting cloud metadata would occasionally hang

---

cmd/newrelic-infra/newrelic-infra.go
internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/cmdchannel/handler/featureflag_handler.go
internal/agent/cmdchannel/service_test.go
internal/feature_flags/feature_flags.go
internal/feature_flags/test/ff_fakes.go
pkg/config/config.go
pkg/helpers/detection/detection.go
pkg/integrations/v4/emitter/emitter_test.go
pkg/integrations/v4/emitter/emitter_v4.go
pkg/metrics/docker_sampler.go
pkg/metrics/docker_sampler_test.go
pkg/metrics/docker_sampler_windows_test.go
pkg/metrics/process/cache.go
pkg/metrics/process/harvester_linux.go
pkg/metrics/process/sampler_linux.go
pkg/metrics/process/sampler_linux_test.go
pkg/metrics/procs.go
pkg/metrics/procs_windows.go
pkg/metrics/procs_windows_test.go
pkg/metrics/sampler/matcher.go
pkg/metrics/sampler/matcher_test.go
pkg/metrics/storage/storage_sampler_test.go
pkg/metrics/types/process_sample.go
test/fixture/sample/assert.go
test/fixture/sample/processes.go
test/fuzz/integration_payload/fuzz.go
test/harvest/processmetrics_test.go

Process sample is disable by default. It could still be enabled/disabled via feature-flag and config-option.
Precedence is:
1. config option
2. feature flag
3. default behaviour (exclude process samples)

Process sampling disabled by default with feature-flag & config-option

---

internal/agent/agent_test.go

Sometimes when running unit test from agent_test.go would end up in a race condition as the cloud metadata plugins would try and run.

fix: tests now don't run into a race condition when testing on AWS

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_test.go
pkg/integrations/v4/logs/loader_test.go

This PR adds support in the Infrastructure Agent to support multiple `entity.guids` in the log records forwarded by the Log Forwarder. The current implementation overwrites the `entity.guid` field of the original log record. If that record came from the APM, for instance, this means that the APM's `entity.guid` is lost forever and replaced by the INFRA one.
This implementation introduces the INFRA `entity.guid` as `entity.guid.INFRA` instead, to avoid this collision. The Logging ingest pipeline will then take care of parsing any `entity.guid` or `entity.guid.*` attributes and glueing them together into a single `entity.guids` attribute.

LOGGING-2546: Support for multiple entity.guid in the Log Forwarder

---

pkg/metrics/heartbeat_sampler.go
pkg/metrics/heartbeat_sampler_test.go

Becuase we were not using a pointer, the entityKey and timestamp were missing from the sample and so they get dropped
Update: changed the for HeartbeatSample to include BaseEvent instead of having itself define those required properties

fix: heartbeat samples were being dropped

---

internal/agent/plugin.go

When an integration such as Flex generates an event that contains a timestamp do not overwrite the timestamp.
If the timestamp is nil generate the timestamp with `time.Now().Unix()` as it does currently.
Tested changes with a custom build of the agent, functionality works as intended.
cc/ @carlosroman @jfjoly @fryckbos

feat: use existing timestamps when available

---

.github/workflows/test.yml
.gitignore
build/infra_build.mk

Added ability to send code coverage results to [coveralls.io](https://coveralls.io/github/newrelic/infrastructure-agent). At the moment have only added the ability to do this for Linux builds. I've set it up so next step (if we find this useful) is to add Windows code coverage as well to the build.

ci: adding code coverage steps to send data to coveralls.io

---

internal/agent/agent.go
internal/agent/event_sender_test.go
internal/agent/event_sender_vortex_test.go
internal/agent/patch_sender_test.go
pkg/ctl/sender/client_docker_test.go
pkg/ctl/shutdown_linux_test.go

Some tests around `agent.go` were failing because of a race condition. It looks like we access `agentKey` from different go routines and sometimes change the value as well. Have swapped it from being a `string` to an `atomic.value`.

fix: fixed race condition accessing agentKey in agent ctx

---

internal/agent/agent.go
pkg/config/config.go
pkg/config/defaults.go

This PR allocates a configurable inventory queue in the same fashion as metrics/events.
By doing so inventory processing flow won't block unless queue length is reached.
By defaults sets inventory queue size to 10 datasets.
> I won't make this testable as inventory for integrations is likely to EOL soon.
ToDo:

Allocate inventory queue

---

internal/agent/agent.go
internal/agent/cmdchannel/handler/featureflag_handler.go
internal/agent/cmdchannel/service_test.go
pkg/config/config.go
pkg/config/defaults.go
pkg/trace/features.go

This sets inventory processing queue back to synchronous (blocking call on 0 length channel).
Also adds support for this feature to be enabled or disabled via command-api.
Desired behaviour is:
- default inventory queue len is 0 (current agents size)
- inventory queue can be modified via usual config file/env-var
- this config setup can be disabled via command-api
- when no config setup was provided by user, this feature can be enabled via command-api setting inventory queue value to 100
As this value is set at startup time an agent restart is triggered (not a service restart!) if required.
Also adds an `inventory` *trace* in case a weird case needs to be troubleshooted.

Feature flag support for: non blocking inventory processing queue

---

go.mod
go.sum
internal/agent/bulk_inventories_test.go
internal/agent/delta/store.go
internal/agent/delta/store_test.go
internal/plugins/linux/dpkg.go
internal/plugins/linux/rpm.go
internal/plugins/linux/sysctl_subscriber.go
internal/plugins/linux/users.go
pkg/integrations/v4/logs/cfg_watcher.go
pkg/integrations/v4/manager.go
pkg/plugins/files_config.go
test/harvest/sysctl_test.go

The reasons for this PR is to update fsnotify as latest version as some libraries we want to use have issues with old versions of this library (like spf13/cobra).

chore: upgraded fsnotify to v1.4.9

---

pkg/integrations/v4/manager_test.go

Problem: Sometime we had an issue that `TestManager_SkipLoadingV3IntegrationsWithNoWarnings` was failing. I did a research and caught that previous test `TestManager_ProtocolV4` was producing an error in logs and was overlapping in runtime with `TestManager_SkipLoadingV3IntegrationsWithNoWarnings`. This is why we had issues with different tmp folder and file name compared to test we run.
Cause: Shared log instance (my guess)
Solution: Channel added to wait for test to finish `manager.Start()` and only then start another test.

test: correct flaky TestManager_SkipLoadingV3IntegrationsWithNoWarnings test

---

go.mod
go.sum
internal/agent/cmdchannel/handler/featureflag_handler.go
internal/agent/cmdchannel/service_test.go
pkg/config/config.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/emitter/emitter.go
pkg/integrations/v4/emitter/emitter_test.go

The agent now register entities before send metrics/inventory/event to backend.
Integration under `protocol_v4`
Feature flag to enable it: `feature:  dm_register_enabled: true`. 
Customer config has precedence over command api.

feat: register entities under FF

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_template.go
pkg/integrations/v4/logs/cfg_test.go
pkg/integrations/v4/logs/loader_test.go
pkg/integrations/v4/logs/logs/cfg.go
pkg/integrations/v4/logs/logs/cfg_template.go
pkg/integrations/v4/logs/logs/cfg_test.go
pkg/integrations/v4/logs/logs/cfg_watcher.go
pkg/integrations/v4/logs/logs/cfg_watcher_test.go
pkg/integrations/v4/logs/logs/loader.go
pkg/integrations/v4/logs/logs/loader_test.go
pkg/integrations/v4/logs/logs/output_fb.go
pkg/integrations/v4/logs/logs/output_fb_test.go

Added Path_Key to config so we capture name of file being tailed.

Added Path_Key to tail config

---

go.mod
go.sum
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go

Send now queues received data and lazy loads its processing routine in background.

refactor: emitter async processing

---

go.mod
go.sum
internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/event_sender_test.go
internal/agent/mocks/AgentContext.go
internal/plugins/testing/agent_mock.go
pkg/entity/host/host.go
pkg/integrations/legacy/runner.go
pkg/integrations/legacy/runner_test.go
pkg/integrations/legacy/utils.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_bench_test.go
pkg/integrations/v4/dm/emitter_no_register.go
pkg/integrations/v4/dm/emitter_test.go
pkg/integrations/v4/emitter/emitter_test.go
pkg/metrics/process/sampler_linux_test.go
pkg/plugins/http_server_test.go

This logic is required by entity registration, therefore we need it decoupled form agent package
Replaces: https://github.com/newrelic/infrastructure-agent/pull/127

refactor: extract agent key logic to package

---

internal/agent/cmdchannel/handler/featureflag_handler.go
pkg/config/config.go

Deleting dead and misleading code.
`Features` config option should be used instead:
```
features:
dm_register_enabled: true
```

fix: remove misleading config

---

pkg/helpers/fingerprint/fingerprint.go
pkg/helpers/fingerprint/fingerprint_test.go
pkg/sysinfo/cloud/cloud.go

This is related to #94 - the fingerprint harvester should fail if the host is running on the cloud and the cloud API couldn't be reached or returned an error. If not, the host could start reporting as a different entity.

fix(fingerprint): handle cloud harvester errors

---

pkg/integrations/v4/supervisor.go

Fixes trace for log forwarder where line would be empty otherwise.
LogFw tracing feature hasn't been released yet, so *consider this for next release*.

fix: log forwarder trace

---

pkg/entity/known_ids.go
pkg/entity/register/worker.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go

This PR will cache the registered entity ids and also fixes an issue where the batch structure for register entities was not clean

Cache registered ids and fix the register batch loop

---

internal/integrations/v4/integration/definition_test.go
internal/integrations/v4/integration/integration.go
internal/integrations/v4/integration/integration_test.go
internal/integrations/v4/runner/group_test.go
internal/integrations/v4/runner/runner_test.go
pkg/integrations/cmdrequest/handler.go
pkg/integrations/v4/config/config.go

Renaming `Name` var to express functionality, so it can be distinguished from `IntegrationName`.
Doc reference: https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format

refactor: rename v4 config Name to InstanceName

---

Makefile
build/embed_ohis.mk

This is needed because of an issue where old build scripts would have the wrong path when importing `nri-integrations` file. Due to this bug it meant that when we updated the OHI version in `nri-integrations` it wasn't getting picked up correctly.

ci: Updated path to build scripts in Makefile

---

pkg/backend/identityapi/register_client.go
pkg/backend/telemetryapi/aggregated_metrics_test.go
pkg/backend/telemetryapi/config.go
pkg/backend/telemetryapi/config_test.go
pkg/backend/telemetryapi/harvester.go
pkg/backend/telemetryapi/harvester_test.go
pkg/backend/telemetryapi/metrics_batch_test.go
pkg/backend/telemetryapi/metrics_test.go
pkg/backend/telemetryapi/request.go
pkg/backend/telemetryapi/request_test.go
pkg/backend/telemetryapi/spans_batch_test.go
pkg/backend/telemetryapi/spans_test.go

This PR adds a worker pool to process HTTP requests. This should speed up the sending of DM to the backend. For more details see #125.

feat: telemetryapi client now has a worker pool to perform HTTP requests

---

cmd/newrelic-infra/newrelic-infra.go
pkg/integrations/v4/manager.go
pkg/integrations/v4/manager_slow_test.go
pkg/integrations/v4/manager_test.go

Enables stop-integration handler for commad-api.
It also provides safe mock calls when caller arguments are not enough, therefore on race conditions extra calls won't fail.

feat: inject cmd-channel stop integration handler

---

go.mod
go.sum

Fixes issues with NFS samples not showing up and log message like:
```
time="2020-10-14T12:34:13Z" level=debug msg="unable to retrieve NFS stats" component=NFSSampler error="error retrieving mounts for NFS: invalid NFS per-operations stats: [NULL: 1 1 0 44 24 0 0 1 0]"
```
This is a bug within the underlying Prometheus NFS library, see https://github.com/prometheus/procfs/issues/275

fix: NFS invalid stats

---

pkg/metrics/process/sampler_linux.go
pkg/metrics/process/sampler_linux_test.go
pkg/metrics/sampler/matcher.go
pkg/metrics/sampler/matcher_test.go
pkg/metrics/sampler/sampler.go
pkg/metrics/types/process_sample.go
test/fixture/sample/processes.go

This fixes issue #167, where process samples that have been decorated with Docker labels are not filtered.

fix: Samples from Docker process now correctly filtered as host processes

---

cmd/newrelic-infra/newrelic-infra.go
pkg/backend/telemetryapi/config.go
pkg/backend/telemetryapi/harvester.go
pkg/backend/telemetryapi/metrics_batch_test.go
pkg/backend/telemetryapi/request.go
pkg/backend/telemetryapi/request_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/defaults.go
pkg/integrations/v4/dm/sender.go
pkg/integrations/v4/dm/sender_test.go
pkg/integrations/v4/dm/telemetry.go

Embedded telemetry API now split DM submission by number of entities following requested driven contract limitations.
A new internal configuration is added with a default value of `300` entities per batch request sent to New Relic. That will cover almost all maximum on http header values. [Ref](https://stackoverflow.com/questions/686217/maximum-on-http-header-values/8623061#8623061)
For more informations on the limits see the [docs](https://docs.newrelic.com/docs/telemetry-data-platform/get-data/apis/metric-api-limits-restricted-attributes).
Resolve #123

feat: DM submission split request by max amount of entities

---

go.mod
go.sum

Fixes build for Mac (not supported by NR), broken by latest gopsutil update.
Next gopsutil release fixes this issue, see: goshttps://github.com/shirou/gopsutil/issues/958
For now this workaround points to the latest `sys` before the breaking change: golang/sys@85ca7c5,  breaking change at golang/sys@5766fd3.

fix: Darwin build

---

pkg/integrations/legacy/runner_test.go

Restoring a test that was commented out.

test: restore TestGenerateExecWithEnvVars

---

cmd/newrelic-infra/newrelic-infra.go
internal/agent/event_sender.go
pkg/backend/telemetryapi/config.go
pkg/backend/telemetryapi/config_test.go
pkg/backend/telemetryapi/harvester.go
pkg/backend/telemetryapi/harvester_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/defaults.go
pkg/integrations/legacy/runner_test.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go
pkg/integrations/v4/dm/sender.go
pkg/integrations/v4/dm/sender_test.go
pkg/integrations/v4/dm/telemetry.go
pkg/integrations/v4/manager_test.go
pkg/metrics/procs_windows_test.go
pkg/metrics/sampler/matcher_test.go

The telemetryapi embedded in the agent now limits the amount of queued entities by configuration.
This feature is tended to avoid memory consumption in case metrics could not be submitted to NR.
Resolve #126

feat: limit amount of queued entities to be submitted

---

build/nri-integrations

This PR syncs the nri-docker integration shipped with the infra agent with version 1.3.3, which ships a fix for Fargate metadata.

Update nri-docker to v1.3.3

---

build/nri-integrations

Main new feature for flex is [HTML parsing](https://github.com/newrelic/nri-flex/pull/232). Have checked the diff between `v1.3.6` and `v1.3.5` and happy that changes should not affect existing behavior. There are some changes to experimental functions though.

feat: Updated nri-flex to v1.3.6

---

build/nri-integrations

To be merged when nri-docker v1.4.0 is released.

Update nri-docker to 1.4.0

---

.github/workflows/codeql.yml
pkg/metrics/docker_sampler.go

This PR enables [GitHub code scanning](https://github.blog/2020-09-30-code-scanning-is-now-available/) which is a useful tool for spotting potential security vulnerabilities. I've fixed a couple that looked very straight forward but the others will require a larger refactor.

ci: Enabled GitHub code scanning tool on the repo

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_test.go
pkg/integrations/v4/logs/loader_test.go

Removes deprecated "folder" parameter from the Log Forwarder integration. This parameter was originally included during the beta phase, but was later removed when we discovered that we could use wildcards when specifying a file path in FluentBit.

[LOGGING-2544] Removes deprecated folder parameter

---

internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/service/service.go
internal/agent/cmdchannel/service/service_test.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
pkg/backend/commandapi/client.go
pkg/backend/commandapi/client_test.go

- replace ACK mechanism from ID (int) to Hash (string)
- ACK every time hash is received (not just once)
- for cmds with hash, run only those which weren't already successfully ACKed

command API spec updates

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/envvar/envvar.go
pkg/config/envvar/envvar_test.go
pkg/config/loader/config.go
pkg/config/loader/config_test.go
pkg/databind/pkg/databind/config.go
pkg/integrations/v4/manager.go
pkg/integrations/v4/manager_test.go

Configuration env-vars replacement for integrations, as done for the agent config.

Env-vars replacement for integrations

---

pkg/config/envvar/envvar.go
pkg/config/envvar/envvar_test.go

Prior to replace env-vars within config files comments are removed. Therefore env-vars within commented lines are not expanded.

Drop comments from config files

---

pkg/config/config.go
pkg/config/config_test.go
pkg/plugins/agent_config.go
pkg/plugins/agent_config_test.go
test/fixture/inventory/expect.go

- agent-config plugin serialising now avoids non public config fields.
- agent-config plugin now submit inventory items in config format, ie. snake-case as YAML (instead of previous camel-case variable name).

fix: agent config plugin serialising only public fields

---

pkg/config/config.go
pkg/config/config_test.go
pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_test.go
pkg/license/license_test.go

- Adds `fedramp: true` flag.
- Removes `gov` license key prefix handling, as there are no such prefixes.
Details on endpoints: https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints
Solves https://github.com/newrelic/infrastructure-agent/issues/278

feat: add fedramp flag & remove gov license prefix

---

internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
pkg/integrations/cmdapi/cmdapi.go
pkg/integrations/cmdapi/cmdapi_test.go

For security reasons, command channel won't allow arbitrary integration executions. These ones should be listed in the allow-list.

feat: deployment experience integration allow list for cmd API

---

pkg/config/envvar/envvar.go
pkg/config/envvar/envvar_test.go
pkg/integrations/legacy/registry.go

RemoveYAMLComments considering hashtag within strings as comment.
Golang does not support negative lookaheads https://github.com/golang/go/issues/18868
There's an alternative library https://github.com/dlclark/regexp2 but here we are sticking to stdlib.
For this reason it's required:
- several regexes
- several capture groups that will be discarded
We are not trimming whitespaces for simplicity.
---
This also logs the (previously shadowed) original error on config error.

fix: RemoveYAMLComments considering hashtag within strings as comment

---

assets/examples/logging/parsers.conf
build/.goreleaser.yml
build/embed/fluent-bit.mk
build/embed/fluent-bit.version
build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs
build/windows/scripts/embed_ohis.ps1
build/windows/scripts/functions.ps1

This PR will update the pipeline for building infra-agent packages to be able to download the fluent-bit component and newrelic fb output plugin from the new locations

Update logging download urls

---

build/embed/fluent-bit.version

This PR will increase the version of the fluent-bit that is embed in the infra-agent packages

ci: updated fb version

---

build/nri-integrations

Bumping windows service version to v0.2.0-beta
https://github.com/newrelic/nri-winservices/releases/tag/v0.2.0-beta

feat(integrations): bump winService

---

build/.goreleaser.yml

This PR will fix the issue with the new packages conflicting with newrelic-infra
In the old pipeline we defined a conflict with pkg newrelic-infra for packages that were suffixed. e.g. newrelic-infra-rc1.
Since we don't have the suffix anymore, we should remove the conflicts

ci: fixed wrong pkg conclits config

---

build/embed/fluent-bit.version

This PR will increase the fluent-bit version to 1.7.3 and also the newrelic output plugin to 1.4.6

ci: increase the logging tool version

---

build/container/Dockerfile

This PR will upgrade the version of the curl package which is causing now failure in the pipeline

ci: upgrade curl for docker image

---

build/container/Dockerfile

By setting the env `NRIA_CONNECT_ENABLED` to `false`, we prevent the agent from creating host entities  when running as a sidecar of `nri-kube-events`.
Thanks to @varas for pointing this out!

container/k8s-events-forwarder: set ConnectEnabled to false

---

build/embed/integrations.version

Bumps the integration to v1.6.0 
This version contains a change in the way some existing metrics are calculated. All details in the [Release notes](https://github.com/newrelic/nri-docker/releases/tag/v1.6.0)

feat(nri-docker): bump nri-docker to v1.6.0

---

build/embed/fluent-bit.version

Rollback FB versions to:
- Linux: output plugin to 1.1.0, FluentBit to 1.3.0
- Windows: output plugin to 1.4.6, FluentBit to 1.4.1

fix: FB libssl issue

---

docs/README.md

Documentation on how to configure processing pipeline values to avoid reaching `full queue` issues.

docs: tuning processing limits

---

go.mod
go.sum

Fixes CVE-2020-14040: golang.org/x/text: possibility to trigger an infinite loop in encoding/unicode, see: avd.aquasec.com/nvd/cve-2020-14040

fix: CVE-2020-14040

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

This PR closes https://github.com/newrelic/infrastructure-agent/issues/85 by removing the `CODE_OF_CONDUCT` file and updating the `README` header to point to the correct image.

docs: fix repolinter issues

---

build/embed/integrations.mk
build/embed/integrations.version

The file Structure of POMI for the tar.gz changed since it was different from all the remaining integrations.
Example https://github.com/newrelic/nri-prometheus/releases/tag/v2.6.1
- Old 
https://github.com/newrelic/nri-prometheus/releases/download/v2.3.0/nri-prometheus_linux_amd64_2.3.0.tar.gz
- New 
https://github.com/newrelic/nri-prometheus/releases/download/v2.6.0/nri-prometheus_linux_2.6.0_amd64.tar.gz

fix(pomiURL): standardize URL

---

pkg/integrations/v4/manager_test.go

Hook addition to logrus is delegated to the  own library instead of doing from the test.

Fix race condition

---

assets/examples/logging/windows/winlog.yml.example

Updated the winlog.yml sample. Previous PR had some channels consolidated into one entry, but that causes duplicate log entries so breaking them out. It also prohibits individual tagging.

Updated Winlog.yml Sample

---

pkg/integrations/configrequest/handler.go
test/cfgprotocol/agent/emulator.go
test/cfgprotocol/cfgprotocol_test.go
test/cfgprotocol/testdata/go/spawner.go
test/cfgprotocol/testdata/scenarios/scenario5/nri-config.json
test/cfgprotocol/testdata/scenarios/scenario5/settings.yml

This PR adds the config template and passthrough environment variables to the spawned integrations of the config protocol . This will allow spawned integrations to use the config parameter of configuration as they do when spawned from config files.

feat: add config template and passthrough env to child runners

---

internal/agent/cmdchannel/runintegration/runintegration_test.go
internal/integrations/v4/integration/integration.go
internal/integrations/v4/integration/integration_test.go

Context: Currently an integration has no way to know which is the interval configured for it to be launched.
This PR adds an environment variable to integrations called `NRI_CONFIG_INTERVAL` which has the interval configured for that integration. So the integration can read this env variable and have that context if needed.
One of the use case is detailed in this [doc](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2073657633/Config+generator+refinement) and will allow spawned integrations to inherit the interval from the parent (generator) one.

feat: pass the interval though env var to integrations

---

pkg/integrations/v4/emitter/emitter.go

Adds the context of the parent integration if exist. 
Replaces the log field `name` for `integration_name` to be similar to the fields in the runner.go

feat: add cfg parent context to emmiter logs

---

build/embed/integrations.version

This version upgrades most of the dependencies used by the project.
See the changelog here: https://github.com/newrelic/nri-prometheus/releases/tag/v2.7.0

Bump bundled nri-prometheus to v2.7.0

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/defaults.go

* feat: add identity and command channel gov endpoints
This will add default gov endpoints for the identity api and command channel api.

Add identity and command channel gov endpoints (#529)

---

internal/statusapi/statusapi_test.go

Increasing delay to avoid failures on busy boxes (like CI ones).

fix: flaky test - time race

---

pkg/config/config.go
pkg/config/config_linux.go
pkg/config/config_windows.go
pkg/config/defaults.go
pkg/integrations/v4/logs/loader_test.go

This PR will change the default location for fluent-bit executable on Linux
from:
`/var/db/newrelic-infra/newrelic-integrations/logging/fluent-bit`
into:
`/opt/td-agent-bit/bin/td-agent-bit`
Windows path remain the same.

feat: changed location from where the agent executes fluent-bit

---

build/container/Dockerfile
test/packaging/ansible/roles/repo-setup/tasks/repo-Amazon.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-CentOS.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Debian.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-RedHat.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Suse.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Ubuntu.yaml
test/packaging/ansible/roles/repo-setup/vars/main.yaml

problem: we set repository for each run and if we want to execute tests with testing/staging/prod repos, we have to clean manually boxes from old repos.

test: add cleanup for repository before adding new one in installation tests

---

pkg/integrations/v4/logs/cfg.go

Customers are experiencing 403s because the logging endpoint is not complete.  This PR fixes the endpoint

fix: Fix logging fedRamp endpoint

---

internal/socketapi/socketapi_test.go
internal/statusapi/statusapi_test.go

I'll be restoring these properly in the unify APIs work

test: skip time race affected tests

---

.github/workflows/prerelease_linux.yml
.github/workflows/prerelease_staged_publish.yml
.github/workflows/release.yml
.github/workflows/release_staged.yml
build/.goreleaser.yml
build/embed/fluent-bit.mk
build/embed/fluent-bit.version
build/upload-schema-linux-rpm.yml

Added fluent-bit as infra-agent package weak dependency. If the fb package `td-agent-bit` is not found, the agent installation will not be interrupted.
For distributions that do not support weak dependencies ( rpm version < 4.12.0 ) for fb package is added as a required dependency:
* Red Hat 7
* Centos 7 
* Amazon Linux 2
Publish action is upgraded to latest version which uses `centos-8` as base image. The version of `createrepo` included in `debian buster` based image didn't support rpm weak dependencies.
Amazon Linux 2 rpm packages will be distributed from their own repository (until now centos-7 one was used) as FB has separated packages for AL2.

ci: fluentbit as agent pkg dependency

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/defaults.go

The shim for DM in infra-api is no longer needed for gov customers as gov-metric-api has been launched some time ago. I'm following the same pattern for the rest of the gov URLs, though I know there could be some cleanup here as to how they are generated. This seems easier / cleaner.

add gov metric API URL

---

internal/agent/connect_service.go

We cannot see in the info logs if the agent passed the point of performing the disconnect call

added log line when disconnect call finished

---

assets/examples/infrastructure/newrelic-infra-template.yml.example
internal/agent/event_sender.go
internal/httpapi/httpapi_test.go
pkg/config/config.go
pkg/trace/features.go

Add a trace to log non dimensional *metrics* payload submissions to NewRelic platform.
This trace is disabled by default, it should be enabled as defined below.
Public link: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#debug-variables
Example: https://github.com/newrelic/infrastructure-agent/blob/master/assets/examples/infrastructure/newrelic-infra-template.yml.example#L704
Via YAML config:
```yaml
trace:
- v3.submission
```
Or env-var:
```sh
NRIA_TRACE="v3.submission"
```

Trace non dimensional metrics payload submissions

---

pkg/metrics/sampler/matcher_test.go
pkg/trace/trace.go

Convert logged trace message: field+msg into structured fields `feature` + `msg`.
Current trace format:
```
time="2021-06-29T10:07:21+02:00" level=trace msg="[v3.submission] [{\"EntityID\":40716074594850361,\"IsAgent\":true...
```
New structured format:
```
time="2021-06-29T10:07:21+02:00" level=trace feature="v3.submission" msg="[{\"EntityID\":40716074594850361,\"IsAgent\":true...
```

feat: structure traces feature into proper field

---

cmd/newrelic-infra/newrelic-infra.go

Fixes regression mixing up enablement flags from HTTP APIs: status and data ingest.

fix: HTTP APIs enablement flags

---

test/automated/ansible/roles/install-gpg/tasks/main.yml

Fixes GPG package name for CI infra Debian Buster boxes throwing error `No package matching 'gpg' is available`.
`gpgv` only supports verifying signatures, but that's enough.

fix: CI infra gpg for debian buster

---

test/automated/ansible/install-requirements.yml
test/automated/ansible/roles/install-gpg/tasks/main.yml

Fixed: CI infra replace gpgv with gnupg2 for debian buster
We actually need `gpg` command available in the boxes.

CI infra: replace gpgv with gnupg2

---

internal/httpapi/httpapi_test.go

It seems like CI busy boxes may find 10ms short in time for local HTTP roundtrip.

test: increase status reachability timeout

---

build/embed/integrations.version

Bumps nri-flex to [1.4.2](https://github.com/newrelic/nri-flex/releases/tag/v1.4.2) fixing Flex CVE-2020-29652

chore: bump nri-flex

---

.github/workflows/prerelease_staged_publish.yml
.github/workflows/release_staged.yml

Be able to release (staged version) tarballs `targz` per OS: either `linux`, `macos` or `all` (both).

Split tarball staged releases per OS

---

internal/agent/agent.go
pkg/config/config.go

Out memory profiler is dumping heap in the beginning of runtime.
Add interval heap dump over agent runtime
- We add new config option `MemProfileInterval` `yaml:"mem_profile_interval" envconfig:"mem_profile_interval" ` that will be set automatically if `MemProfile` present. Default value is 300 seconds (5 minutes) and can be configured by user. 
- If `MemProfile` variable is set, agent will start creating heap profile each `MemProfileInterval` seconds and save it in the path stored in the variable like PATH_000000300s, PATH_000000600s where 000000300s is agent uptime mark.

feat: add memory profiling over time

---

.github/workflows/release.yml
.github/workflows/release_staged.yml

Fixes missing checkout previous to run purge CDN script.
See: https://github.com/newrelic/infrastructure-agent/runs/3019770823?check_suite_focus=true

Missing CI checkout previous to purge CDN

---

internal/agent/agent.go

- Log truncated or dropped events as warnings
- Log discarded events by matching rules in debug (will only show up in verbose mode)

Log truncated or dropped events

---

pkg/integrations/v4/dm/lazy_harvester.go
pkg/integrations/v4/dm/lazy_harvester_test.go
pkg/integrations/v4/dm/sender.go

This avoids loading the telemetry-api (dimensional metrics) harvester right away. It'll be lazy loaded on its first usage instead.

feat: lazy loaded DM harvester

---

build/embed/integrations.version

Updating nri-prometheus to use https://github.com/newrelic/nri-prometheus/releases/tag/v2.8.0

Update nri-prometheus to 2.8.0

---

.github/workflows/prerelease_macos.yml
build/ci.mk
build/install_macos_dependencies.sh
build/upload_artifacts_gh.sh

Run macos build in macos runner to avoid missing libraries errors when cross compiling for macos with CGO enabled.

fix: run macos pre-release in macos runner

---

build/container/Dockerfile
internal/agent/agent.go
internal/agent/agent_test.go

* Inventory reap and submission disabled if `forward_only` is enabled
* Container curl version updated to `7.78.0-r0`

fix: don't send inventory if fwd only is enabled

---

internal/integrations/v4/executor/executor.go
internal/integrations/v4/executor/executor_test.go
internal/integrations/v4/testhelp/channels.go

After `executor.Execute()` calls `OutputSend.Close()` there are a couple channels that might be handled out of the Execute() context, I noted these down on the test code.
It'd be nice to build a larger scope leak test covering those too.

Fix executor.Execute Close and test FD leaks

---

internal/plugins/windows/services_test.go
pkg/config/config.go
pkg/config/config_test.go

Fixes https://github.com/newrelic/infrastructure-agent/issues/647 by dereferencing agent-config pointers.
- fix: Config.PublicFields dereferences pointers
- refactor: update tests names

Config.PublicFields dereference pointers

---

internal/integrations/v4/integration/definition_test.go
internal/integrations/v4/integration/integration.go
pkg/integrations/v4/config/config.go
pkg/integrations/v4/config/config_test.go
pkg/integrations/v4/emitter/emitter.go

- Uppercase all ENV vars defined on config file
- add ENV variables to payload log output

Uppercase all ENV vars and add ENV variables to payload log output

---

build/.goreleaser_linux.yml
build/container/Makefile
internal/integrations/v4/runner/runner_test.go
pkg/helpers/contexts/heartbeat.go
pkg/helpers/contexts/heartbeat_test.go

Enable CGO for amd64 assets, to restore missing features. Arm/arm64 CGO required more research as there are some missing libraries and cgo files.
Also in this PR we fix some flaky test.

ci: enable CGO for amd64

---

build/embed/integrations.version

This bumps nri-winservices to v0.4.0-beta to fix memory leak in windows_erxporter

update nri-winservices to v0.4.0-beta

---

build/windows/test.ps1
internal/integrations/v4/executor/executor.go
internal/integrations/v4/executor/executor_test.go
internal/integrations/v4/runner/group_test.go
internal/integrations/v4/runner/runner_test.go
pkg/integrations/v4/manager_test.go

Only environment variables that are present in `NRIA_PASSTHROUGH_ENVIRONMENT` should be passed to integration. These should have precedence over the integration ones.

fix: only pass NRIA_PASSTHROUGH_ENVIRONMENT variables to v4 integrations

---

internal/plugins/linux/rpm.go

By default, /var/lib/rpm/.rpm.lock file is watched to notify
the agent of a RPM package update. In many systems, this file is
not currently used, so a better approach would be to monitor
/var/lib/rpm/Installid directly.

fix: undetected changes on rpm packages inventory

---

internal/plugins/linux/sysctl.go

dmesg complains about reading deprecated sysctl item:
```
[ 1936.917785] ICMPv6: process `newrelic-infra' is using deprecated sysctl (syscall) net.ipv6.neigh.default.retrans_time - use net.ipv6.neigh.default.retrans_time_ms instead
```

fix: do not read sysctl deprecated item

---

build/build.mk
pkg/metrics/storage/storage_sampler_linux.go
pkg/metrics/storage/storage_sampler_linux_test.go
test/harvest/storage_sampler_linux_test.go

`partitionsInfo()` function could also return a map of partitions being the major and minor numbers the key. To keep aligned with the code like the `deviceMapperInfo()`  function, a slice is returned. Nonetheless, any feedback is welcomed.

feat: add partition file scanning

---

.github/renovate.json5

Renovate dashboard is an issue opened by the Renovate bot which
keeps track of the Pull Requests done by the bot. Currently, we use
Zenhub to view and manage PRs.

disable renovate bot dashboard

---

assets/examples/logging/windows/winlog.yml.example

Clean pull request, thanks for your patience @rogercoll.
This standardizes indentation to 2 spaces in this file. Some indentation was at 3 and some at 1 space previously, this was confusing and seems to have led to some issues with YAML parsing as users self-corrected the indentation to the wrong levels.

fix indentation to 2 spaces

---

pkg/helpers/docker_utils.go
pkg/metrics/docker_sampler.go

Moreover, DockerSampler will react to this error and don't log anything if that's the case.

helpers/docker: ignore docker.sock file if it's not a socket

---

internal/plugins/linux/rpm.go

The latest version of rpm in AL2022 does not contain the file:
/var/lib/rpm/Installtid
The lock file is neither updated and the only avaiable file are sqlite
format.

feat: watch rpmdb sqlite file for rpm updates

---

build/goreleaser/linux/al2022_amd64.yml
build/goreleaser/linux/al2022_arm.yml
build/goreleaser/linux/al2022_arm64.yml
build/release.mk
build/upload-schema-linux-rpm.yml
test/automated/ansible/group_vars/localhost/main.yml
test/packaging/ansible/roles/agent-upgrade/tasks/upgrade-RedHat.yaml
test/packaging/ansible/roles/cleanup/tasks/package-RedHat.yaml
test/packaging/ansible/roles/package-install-pinned/tasks/package-RedHat.yaml
test/packaging/ansible/roles/package-install/tasks/package-RedHat.yaml
test/packaging/ansible/roles/package-uninstall/tasks/package-RedHat.yaml
test/packaging/ansible/roles/repo-setup/tasks/repo-Amazon.yaml

Files to build Amazon Linux 2022. Unlike AL2, we still don't have available the `td-agent-bit` package, thus is not mandatory yet.

Build al2022

---

pkg/metrics/storage/storage_sampler.go
pkg/metrics/storage/storage_sampler_test.go

float values of type NaN cannot be encoded into a json file:
https://github.com/golang/go/issues/3480

feat: check StorageSample float pointers

---

internal/agent/status/status_test.go
pkg/integrations/legacy/runner.go
pkg/integrations/legacy/runner_test.go
pkg/integrations/legacy/utils.go
pkg/integrations/v4/dm/emitter_no_register.go

Decorate events with [custom_attributes](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#custom-attributes) as it is done with metrics.
@kang-makes can you confirm the structure below is what you would expect?

fix: decorate events with custom_attributes

---

test/automated/ansible/roles/remove-eol-sources/tasks/main.yml
test/automated/ansible/roles/remove-eol-sources/vars/main.yml

Ansible tasks to change the repositories cannot use ansible builtin
modules as Python3 is not installed by default in Centos8 and we need
to change the repositories url to install it.

feat: use vault repository for Centos8 canaries

---

pkg/config/config.go

Wrong default documentation:
` 	DefaultStorageSamplerRateSecs      = 20`

docs: fix default DefaultStorageSamplerRateSecs

---

build/embed/integrations.version

- The the embedded nri-prometheus now is not using entity synthesis, and retrieves the payload with ignore_entity flag

Bump the embedded nri-prometheus to the last version with ignore_entity

---

internal/integrations/v4/executor/config.go
internal/integrations/v4/executor/config_test.go

Allowing to use regex for `passthrough_environment`
Example
```
passthrough_environment:
- HOME
- SUDO.*  
```
Will add HOME and all SUDO* variables into passthrough

added regex handling for passthrough env

---

internal/agent/agent.go
internal/agent/cmdchannel/fflag/ffhandler.go
internal/agent/cmdchannel/runintegration/runintegration.go
internal/agent/cmdchannel/service/service.go
internal/agent/cmdchannel/stopintegration/stopintegration.go
internal/agent/connect_service.go
internal/agent/delta/store.go
pkg/helpers/helpers.go
pkg/integrations/cmdrequest/handler.go
pkg/integrations/v4/dm/telemetry.go
pkg/integrations/v4/supervisor.go
pkg/metrics/process/harvester_linux.go
pkg/metrics/sampler/matcher.go
pkg/plugins/custom_attrs.go
pkg/sysinfo/hostname/hostname.go
pkg/sysinfo/hostname/hostname_darwin.go
pkg/sysinfo/hostname/hostname_lin_win.go
pkg/trace/features.go
pkg/trace/trace.go
pkg/trace/trace_test.go

Adding `log.Entry` to the tracer allows us to leverage the implementation of Fields in Entry

feat: replace Fields by log.Entry in tracer

---

assets/examples/infrastructure/newrelic-infra-template.yml.example

Minor house keeping on the infra config template. Removing trailing whitespace and fixing some indentation.

Cleanup Infra Config Example

---

internal/plugins/darwin/hostinfo.go
internal/plugins/darwin/hostinfo_test.go
internal/plugins/linux/hostinfo.go
internal/plugins/linux/hostinfo_test.go
internal/plugins/windows/hostinfo.go
internal/plugins/windows/hostinfo_test.go
pkg/helpers/fingerprint/fingerprint_test.go
pkg/sysinfo/cloud/cloud.go
pkg/sysinfo/cloud/cloud_alibaba.go
pkg/sysinfo/cloud/cloud_aws.go
pkg/sysinfo/cloud/cloud_aws_test.go
pkg/sysinfo/cloud/cloud_azure.go
pkg/sysinfo/cloud/cloud_gcp.go
pkg/sysinfo/cloud/cloud_test.go

The goal of this PR is to add `aws_account_id, aws_image_id and aws_availability_zone` in the host plugin. The cloud harvester provides and interface for any of the supported clouds, in order to retrieve the previous values new methods were added.
The PR implements the methods for AWS, Azure and Alibaba

Add additional cloud metadata

---

build/embed/fluent-bit.version

Fluentbit window package for 1.9.1 is now available in https://github.com/newrelic/fluent-bit-package/releases/tag/1.9.1

Update fluentbit windows package version to 1.9.1

---

build/windows/scripts/embed_ohis.ps1

From td-agent-bit.exe to fluent-bit.exe

fix: rename fluent-bit binary name for windows packaging

---

build/embed/fluent-bit.version
build/windows/scripts/embed_ohis.ps1

Hi!
This PR update the fluent-bit version for windows from 1.9.1 to 1.9.3 that fixes some bugs, especially one with the lua filter we use to filter logs by their event ids.
Also removed a rename that is not necessary anymore (we're doing it on our pipeline) and the binary is fluent-bit.exe and not td-agent-bit.exe anymore.
Regards!

feat: update fluent-bit version for windows

---

go.mod
go.sum

fixes CVE-2022-23648
Upgrading to a higher version requires https://github.com/newrelic/infrastructure-agent/issues/1144
No breaking changes: https://github.com/containerd/containerd/releases/tag/v1.5.10

chore: update containerd version

---

build/embed/integrations.version

Bump `nri-docker` integration to v1.7.0
For further details, you can take a look at the [release notes](https://github.com/newrelic/nri-docker/releases/tag/v1.7.0).
There's a NR docs draft PR opened https://github.com/newrelic/docs-website/pull/7628 to update it with the proper infrastructure agent release version.

feat: bump nri-docker to v1.7.0

---

build/goreleaser/linux/rhel_9_amd64.yml
build/goreleaser/linux/rhel_9_arm.yml
build/goreleaser/linux/rhel_9_arm64.yml
build/release.mk
build/upload-schema-linux-rpm.yml
test/automated/ansible/group_vars/localhost/main.yml
test/automated/ansible/roles/logrotate/templates/syslog-RH9.j2
test/fixture/inventory/expect.go
test/packaging/ansible/roles/assert-privileged-caps/tasks/check-Linux.yaml

* add RHEL9
* fix: .vm.block_dump not available in all kernels
Packaging tests expect the file /proc/sys/vm/block_dump but this file
will only be available if block I/O debugging is enabled in the kernel.
* fix: binary capabilities assertion
* feat: add rhel amis
Co-authored-by: Roger Coll <rogercoll@protonmail.com>

add support for RHEL9 (#1171)

---

pkg/databind/internal/discovery/docker/docker.go
pkg/databind/internal/discovery/docker/docker_test.go

This PR will fix the docker discovery issue where ip variable was overwritten when multiple ports are exposed to the container.
Now the discovery.Ip and discovery.Port will return the first valid ipv4/port exposed. In case multiple ips/ports exposed from the container, index can be used: discovery.ip.0 discovery.ip.1, etc. (same for port)

fixed docker discovery issue where ip address was overwritten

---

internal/agent/patch_sender.go

From Info level to Debug, if the agent is disconnected this message will
flood the logs with this entry.

feat: change removing inventory log entry level

---

build/embed/integrations.version

Update the bundled nri-prometheus to leverage https://github.com/newrelic/nri-prometheus/releases/tag/v2.16.4

chore(nri-prometheus): update version

---

build/embed/integrations.version

- Bump nri-winservices to last version v0.6.0-beta

Bump nri-winservices to v0.6.0-beta

---

test/automated/ansible/roles/provision-ec2/tasks/main.yml
tools/spin-ec2/main.go

Interactive `ec-spinner` was broken after make `platform` parameter mandatory. This PR fixes it.

test: fix ec2 spinner interactive mode

---

pkg/config/config_darwin.go
pkg/config/config_darwin_amd64.go
pkg/config/config_darwin_arm64.go

In arm based macos the homebrew path has been changed:
From [https://docs.brew.sh/Installation](https://docs.brew.sh/Installation)
```
This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for 
Apple Silicon and /home/linuxbrew/.linuxbrew for Linux) so that you don’t need sudo when you brew install
...
```

NEWRELIC-3109 feat: support homebrew path in arm64

---

.github/workflows/security.yml
go.mod
go.sum

- Fix net package CVE
- Builds the container for the current commit and checks the infrastructure-agent binaries (INTEGRATIONS NOT INCLUDED) with Trivy

NR-50701 Fix net CVE

---

.golangci.yml
pkg/config/config.go
pkg/config/config_test.go
pkg/metrics/process/harvester_darwin.go
pkg/metrics/process/harvester_linux.go
pkg/metrics/process/harvester_unix.go
pkg/metrics/process/sampler_darwin.go
pkg/metrics/process/sampler_linux.go

In an arbitrary Amazon Linux 2 with a very low load all the following PIDs got the "process with zero rss" error:
pids="[2 3 4 5 7 10 11 12 13 14 15 16 17 18 19 21 24 25 26 28 29 30 31 32 33 88 89 90 91 92 93 94 95 138 140 141 144 186 188 190 197 223 241 251 252 303 748 749 750 751 752 753 754 755 1247 1257 1409 1410 8980 9086 9112 9551 9778 9784 10580 10790 11040 11238]"
For each scrape, a log line for each pid is displayed (debug mode):
```time="2022-09-23T09:50:29Z" level=debug msg="Skipped processes." component=ProcessSampler error="process with zero rss"```
This generates a lot of noise in the logs and most probably the processes without rss memory are internal kernel processes that we do not instrument.

NR-54822 refactor: exclude rss process error from logs

---

test/packaging/ansible/roles/agent-host-status-event-assert/defaults/main.yml
test/packaging/ansible/shutdown-and-terminate.yml
tools/aws_logs.sh

context:
- for Smart HNR the agent is performing nrqls to check if agent submited a disconnect request
- for this nrql we calculate a `seconds ago` clause based on the timestamp of ansible ec2 shutdown role execution and the current time of executing the nrql.
- however if the query execution takes longer, the test might miss the "window" of the Sample.
in this fix we delay the seconds ago calculation to the last moment before executing the query and also add a 5 seconds tolerance

fix smar hnr flacky tests

---

build/package/binaries/linux/installer.sh

installer.sh script fails to copy the binaries when upgrading an existing version of the agent.
This is caused by the fact that the newrelic-infra-service process is already running.
This PR will attempt to stop the service before performing the installation

stop the service to allow upgrade with tarball installation

---

internal/plugins/common/cloud.go
internal/plugins/common/cloud_test.go
internal/plugins/common/hostinfo.go
internal/plugins/common/hostinfo_test.go
internal/plugins/darwin/hostinfo.go
internal/plugins/darwin/hostinfo_test.go
internal/plugins/darwin/processorinfo_test_amd64.go
internal/plugins/darwin/processorinfo_test_arm64.go
internal/plugins/linux/hostinfo.go
internal/plugins/linux/hostinfo_test.go
internal/plugins/windows/hostinfo.go
internal/plugins/windows/hostinfo_test.go
pkg/plugins/plugins_darwin.go
pkg/plugins/plugins_linux.go
pkg/plugins/plugins_windows.go
pkg/sysinfo/cloud/cloud_aws_test.go
pkg/sysinfo/cloud/cloud_azure.go
pkg/sysinfo/cloud/cloud_azure_test.go
test/harvest/hostinfo_darwin_test.go
test/harvest/hostinfo_linux_test.go
test/harvest/hostinfo_test.go

- Refactor: 
1. moves duplicated code from HostInfoData to common package that can be used by any
2. decopules cloud harvester
- Add Azure metadata
1. Subscription id
2. Availability zone

NEWRELIC-3023: Add azure metadata

---

pkg/databind/pkg/databind/replacer.go
pkg/databind/pkg/databind/replacer_test.go

This configurations is not working in the current version due to slashed in the labels.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
```
discovery: 
command: 
exec: /var/db/newrelic-infra/nri-discovery-kubernetes --tls --port 10250
match: 
label.app: test
integrations: 
- env: 
CLUSTER_ENVIRONMENT: ${discovery.clusterName}
app: ${discovery.label.app}
dashses: ${discovery.label.with-dashes-tld}
dots: ${discovery.label.with.dots.tld}
url: ${discovery.label.with.dots.tld/and-url}
url_scaped: ${discovery.label.with.dots.tld\/and-url}
exec: /bin/bash -c se
interval: 2s
name: bash-test
```

support for urls in discovery

---

pkg/helpers/contexts/heartbeat.go
pkg/helpers/contexts/heartbeat_test.go

This PR will fix a possible deadlock happening when the heartbeat arrives too late (when AfterFunc is already executed so the timer.C is already consummed)
```
if !ctx.timer.Stop() {
<-ctx.timer.C
```

fix deadlock in heartbeat ctx

---

build/embed/integrations.version

Bump nri-docker to v1.7.6

---

pkg/integrations/v4/supervisor_fb.go
pkg/integrations/v4/supervisor_fb_test.go

The New Relic Logging Platform team has identified an issue that eventually could fill up the disk where the infrastructure agent is installed. This issue is related to the FluentBit plugging. Every time the plugging detects some change in the logging config file or in the hostname of the machine, creates a new config temp file in the temporary directory with the pattern _nr_fb_config#####_. Depending on the plugging configuration, some other temp config files with pattern _nr_fb_lua_filter#####_ could also be created in the same directory. If these files are never removed it could cause a full disk error with the corresponding consequences for the customers.
The code included in this pull request prevents the creation of config temp files indefinitely by placing a limit on the number of …

NR-72398 - Do not let Infra Agent's Fluent Bit config files fill up the disk

---

.github/workflows/component_trivy.yml

See issue with latest Trivy version: https://github.com/aquasecurity/trivy-action/pull/213

ci: pin trivy action version

---

.golangci.yml
cmd/newrelic-infra/initialize/initialize.go
cmd/newrelic-infra/initialize/initialize_darwin_amd64.go
cmd/newrelic-infra/initialize/initialize_darwin_arm64.go
cmd/newrelic-infra/initialize/initialize_linux.go
cmd/newrelic-infra/initialize/initialize_test.go
cmd/newrelic-infra/initialize/initialize_windows.go
cmd/newrelic-infra/newrelic-infra.go
pkg/config/config.go
pkg/config/config_darwin_amd64.go
pkg/config/config_darwin_arm64.go
pkg/config/config_darwin_test.go
pkg/config/config_linux.go
pkg/config/config_linux_test.go
pkg/config/config_windows.go
pkg/config/config_windows_test.go
pkg/config/defaults.go
pkg/integrations/v4/supervisor_fb.go
pkg/integrations/v4/supervisor_fb_test.go

This PR adds 
* a custom `tmp` folder for the Infra Agent, not to use the OS one.
* refactored FB temp files to be stored in the new `tmp` folder

NR-93077 feat: use custom tmp folder

---

.github/actions/external_runner/main.go
tools/provision-alerts/alerts.mk
tools/provision-alerts/create_alerts.sh
tools/spin-ec2/main.go
tools/spin-ec2/main_test.go

Canaries alerts provisioning is broken as the previous version was retrieved from inventory and we don't have that anymore. 
This is a quick&dirty solution to get the previous version using GH API and it's tempñorary as we are moving to Terraform and we'll need to manage it differently.

NR-98861 fix:use GH API to get the previous tag of given tag

---

cmd/newrelic-infra/initialize/initialize_darwin_amd64.go
cmd/newrelic-infra/initialize/initialize_darwin_arm64.go
cmd/newrelic-infra/initialize/initialize_linux.go
pkg/config/config_darwin_amd64.go
pkg/config/config_darwin_arm64.go
pkg/config/config_darwin_test.go
pkg/config/config_linux.go
pkg/config/config_linux_test.go

Only use agent `/tmp` folder in windows. In K8S it might be broken wen fs is mounted as `ro`

fix: use agent tmp folder only in windows

---

internal/agent/agent.go

Logging the limit just logs a static known value.
Instead logging the length of the original data helps us
undestand the size of the attributes being sent to the
forwarder.

Print original length instead of the limit

---

.github/workflows/component_linux_harvest_test.yml

ubuntu-18.04 was deprecated: https://github.com/actions/runner-images/issues/6002

chore: use ubuntu-20.04 runner

---

pkg/config/config.go
pkg/sysinfo/cloud/client.go
pkg/sysinfo/cloud/client_test.go
pkg/sysinfo/cloud/cloud.go

Great blog about Go http timeouts: https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
Considering that cloud metadata endpoints are local and should be very fast (we also perform retries), we set up the default timeout to 30s, it can be parametrized in the future if needed.
Linter issues:
- response body must be closed (bodyclose) -> Request will always fail and function exits before "body" is provided
- global variables -> Already defined, in the future we might want to parametrize the defaultHttpClientTimeout

NR-103816: Cloud metadata client

---

THIRD_PARTY_NOTICES.md
go.mod
go.sum
tools/yamlgen/go.mod
tools/yamlgen/go.sum

Thus, yamlgen dependencies are not included in the main go mod

refactor: create yamlgen go mod

---

.github/workflows/component_molecule_packaging.yml
.github/workflows/release.yml

Pin ubuntu 20.04 to pkg component molecule runner and make molecule depend on purge when releasing.

Pin ubuntu 20.04 to pkg component molecule runner

---

build/embed/fluent-bit.version

Waiting for [this PR](https://github.com/newrelic/newrelic-fluent-bit-output/pull/132) to be released

NR-119605 chore: Bump fluent-bit-plugin to 1.17.1 (Go 1.20.5)

---

pkg/metrics/containerd_sampler.go
pkg/metrics/containerd_sampler_mock_test.go
pkg/metrics/containerd_sampler_test.go

If the container is not running, the execution task is not available.
How to reproduce?
Run the following command twice in an instance with Containerd:
`sudo ctr run docker.io/library/nginx:latest hello`
Error:
`ctr: snapshot "hello": already exists`

NR-122708: handle error when no task is found

---

build/embed/fluent-bit.version
cmd/newrelic-infra/newrelic-infra.go
pkg/config/config.go
pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_template.go
pkg/integrations/v4/logs/cfg_test.go
pkg/integrations/v4/logs/loader_test.go

Issue link: [NR-181605](https://new-relic.atlassian.net/browse/NR-181605)
**Description**
- For log forwarding, a new param - `sendMetrics` is introduced in the newrelic-fluent-bit-output plugin. 
- While constructing the FluentBit config file, the output plugin should contain sendMetrics param if verbose logging is enabled for supervisor via log_filter in the newrelic-infra.yml file.
**Changes**
- the new param is introduced in the template file
- from `config/config.go LogForward`, verbose logging mode is checked and set to this field - `FluentBitVerbose`
- The above `FluentBitVerbose` field is used to check if sendMetrics param should be in fluentBit config file.
**Test cases**
- Test cases for the new changes are added in cfg_test.go and loader_test.go

NR-181605 Add sendMetrics param to newrelic output plugin in FB conf file

---

internal/integrations/v4/runner/group_test.go
internal/integrations/v4/runner/runner.go
internal/integrations/v4/runner/runner_test.go

The infrastructure agent will now log integration execution errors matching the level set for infra-agent logs. 
Before this fix, all integrations logs were output only when the infra-agent level was debug. The integrations warning and info level logs will continue being output only when the agent level is debug.
The infrastructure agent is also capable of filtering the errors of an integration if it's explicitly defined in the log configuration. In this example the errors coming from nri-mssql won't be shown when the agent log is in any level (except debug):
```YAML
log:
exclude_filters:
integration_name:
- nri-mssql
```

Add parser for integration SDK errors

---

cmd/newrelic-infra/newrelic-infra.go
internal/integrations/v4/constants/constants.go
internal/integrations/v4/executor/executor.go
internal/integrations/v4/v3legacy/definitions_repo.go
pkg/integrations/legacy/runner.go
pkg/integrations/legacy/runner_test.go
pkg/integrations/v4/manager.go
pkg/integrations/v4/manager_test.go
test/cfgprotocol/agent/emulator.go

Propagate TEMP_DIR  environment variable to integrations when DefaultIntegrationsTempDir is set up.
This makes the integrations with the SDK version > 3.8.2 to store the cache files in the provided Directory instead of the default `os.Tempdir() + "/nr-integrations"`

Add sdk temp dir (NR-219553)

---

docs/log_configuration.md
internal/integrations/v4/runner/runner.go
internal/integrations/v4/runner/runner_test.go
pkg/config/config.go
pkg/config/config_darwin_test.go
pkg/config/config_linux_test.go
pkg/config/config_test.go
pkg/config/config_windows_test.go

- Exclude integration error logs by default (Except the one causing to exit with status > 1) 
- Allow including the errors by integration using filters.

Exclude integration error logs by default.

---

.github/workflows/component_canaries.yml
.github/workflows/component_canaries_prune.yml
.github/workflows/component_canary_alerts.yml
.github/workflows/component_canary_alerts_delete.yml
.github/workflows/component_prerelease_testing.yml
Makefile
test/canaries/Makefile
test/canaries/alerts/Makefile
test/provision/Makefile
test/provision/README.md

Use makefile relative paths to the current directory

NR-236049: use relative paths for test/provision and test/canaries

---

build/goreleaser/linux/al2023_arm64.yml

fluent-bit supports amzn 2023 arm64 and we'd like to release packages for it too

Enable FB for al2023_arm64.yml

---

.golangci.yml
internal/agent/agent.go
pkg/backend/identityapi/metadata.go
pkg/backend/identityapi/metadata_test.go
pkg/metrics/system_sampler.go
pkg/metrics/system_sampler_test.go
pkg/plugins/plugins_darwin.go
pkg/plugins/plugins_linux.go
pkg/plugins/plugins_windows.go
pkg/sysinfo/hostid/provider.go
pkg/sysinfo/hostid/provider_mock.go
pkg/sysinfo/hostid/provider_test.go
test/harvest/hostmetrics_linux_test.go
test/harvest/hostmetrics_test.go
test/harvest/hostmetrics_unix_test.go
test/infra/agent.go
test/log/log_helper.go

This PR extracts the HostID Provider functionality from the Metadata Provider and it injects into this and the System Sampler.

add host.id to System Sample

---

.github/workflows/prerelease_windows_on_demand.yml

Windows pre-release on demand was missing the file checksum generation and it was broken. This PR adds the checksum generation.

generate checksum files on windows pre-release on demand

---

.github/workflows/prerelease_windows_on_demand.yml

Checkout action v2 and v3 have different behavior regarding checkout path and checksum action is not found.
v2:
```
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\infrastructure-agent\infrastructure-agent\src\github.com\newrelic\infrastructure-agent
```
v3:
```
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\infrastructure-agent\infrastructure-agent
```
This PR adjusts the path to v3

fix local action checksum path

---

pkg/databind/internal/secrets/cyberarkcli.go
pkg/databind/internal/secrets/cyberarkcli_exec_unix.go
pkg/databind/internal/secrets/cyberarkcli_exec_unix_test.go
pkg/databind/internal/secrets/cyberarkcli_exec_windows.go
pkg/databind/internal/secrets/cyberarkcli_exec_windows_test.go

CyberArk CLI on Windows is not currently supported. This PR adds support for it.
```
CLIPasswordSDK.exe GetPassword /p AppDescs.AppID=AppBilling /p Query="Safe=PasswordSafe;Folder=Root;Object=Application1" /o Password 
```
https://docs.cyberark.com/credential-providers/Latest/en/Content/CP%20and%20ASCP/CLI-Application-Password-SDK-EgsSyntax.htm#Examples

support Cyberark on Windows

---

tools/cdn-purge/fastly-purge.go

Fail the purge CDN action if the API call to Fastly fails.

ci: fail if purge CDN fails

---

.github/workflows/component_docker_build.yml
.github/workflows/prerelease_macos.yml
.github/workflows/test.yml
test/harvest/ansible/roles/run-harvest-tests/tasks/main.yml

- remove missing job of broken workflow
- stop publishing `build-*` images on each push. This was causing race conditions when scanning that image for security. 
- replace deprecated `include:` feature in ansible (updated on the fargate task) fixing:
```
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
```

chore: fix pipeline

---

.github/workflows/prerelease_testing.yml
test/packaging/ansible/installation-pinned.yml

- removes pre-release test on demand for macos which was provisioning machines and trying to run tests that make no sense in the current harness, leaving running machines.
- bumps the min version supported by ubuntu 24 for the pin version test, otherwise it fails for that os since there is no package before it.

chore: remove pre-release macos

---

.github/workflows/prerelease_linux.yml
.github/workflows/prerelease_windows.yml

On pre-release, instead of pruning previous canaries we were pruning the recently created ones. This PR fix that
fetching the previous tag and passing it to prune component.

NR-262015 ci: fix prune previous canaries on pre-release

---

pkg/config/config.go
pkg/config/config_linux_test.go
pkg/plugins/integrations_only.go
pkg/plugins/plugins.go
pkg/plugins/plugins_darwin.go
pkg/plugins/plugins_linux.go
pkg/plugins/plugins_test.go
pkg/plugins/plugins_windows.go
test/harvest/integrations_only_test.go

Adds a new mode to the Infra Agent to cover the scenario where the customer wants Integration Entities, and Host decoration but not Host Entity created by the Infra agent.
New Mode: integrations_only
The Infra Agent will send the running mode as a new inventory entry.
source: metadata/infra_agent
with this format: "metadata/infra_agent" : {"integrations_only": ""}
Infra Platform will read the running mode inventory entry when Integrations Only it will not send the Host Entity to Entity Platform

Add new integrations_only agent mode.

---

pkg/integrations/v4/logs/cfg.go
pkg/integrations/v4/logs/cfg_template.go
pkg/integrations/v4/logs/cfg_test.go

Adds a new config parameter which is `Multiline.Parser` to the `INPUT` block of fluent-bit config which enables the user to parse multiline logs. And this can be enabled by configuring the `multilineParser` for the log file in the `logging.yml` like below.
```
logging.yml 
-  name: java.log
file: /var/log/javalogs.log
multilineParser: java
attributes:
logtype: java_logs
```
```
fluent-bit.conf
[INPUT]
Name tail
Path /var/log/javalogs.log
Buffer_Max_Size 128k
Mem_Buf_Limit 16384k
Skip_Long_Lines On
Multiline.Parser java        
Path_Key filePath
Tag  java.log
DB   /var/db/newrelic-infra/newrelic-integrations/logging/fb.db
```
**Note:** Fluent-Bit already has built-in multiline parsers which are java, go, python, docker and cri. And the above changes will only support fluent-bit built-in …

NR-279356: Add new multiline parser config param to logging config

---

.github/workflows/component_macos_harvest_test.yml
.github/workflows/component_macos_linter.yml
.github/workflows/component_macos_unit_test.yml
pkg/config/config.go
pkg/config/defaults.go
pkg/metrics/process/sampler_darwin.go
pkg/metrics/process/sampler_darwin_test.go
pkg/metrics/process/sampler_linux.go
pkg/metrics/process/sampler_linux_test.go
pkg/metrics/procs_windows.go
pkg/metrics/procs_windows_test.go

Allow disabling process container decoration.
New config option will be enabled by default, not to break any existing environment.
To disable it:
```yaml
process_container_decoration: false
```
This will help to troubleshoot existing environments with problems without disabling ProcessSample

NR-288387 feat: config option to disable container decoration

---

internal/integrations/v4/integration/definition.go
internal/integrations/v4/integration/definition_test.go
internal/integrations/v4/integration/integration_test.go
internal/integrations/v4/runner/group_test.go

Make discovered config temp file name be calculated with content's md5 to get always same args and avoid miscalculating the integrationID.

Make discovered config temp file name be calculated with content's md5

---

build/windows/package_zip.ps1

We have renewed the certificate to sign Windows packages. After importing it to the Windows host, the fingerprint of the certificate is used to access it. This is hard-coded in this script (it should be changed to be an env var from a GH secret)

Fix wincertPath to new cert

---

build/embed/integrations.version

bump to latest version of integration

chore: bump nri-winservices to v1.0.2

---

build/embed/fluent-bit.version
build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs
build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs
build/windows/scripts/embed_ohis.ps1
build/windows/scripts/functions.ps1
cmd/newrelic-infra/newrelic-infra.go
internal/agent/cmdchannel/fflag/ffhandler.go
internal/agent/cmdchannel/fflag/ffhandler_test.go
pkg/integrations/v4/supervisor_fb_conf_linux.go
pkg/integrations/v4/supervisor_fb_conf_linux_test.go
pkg/integrations/v4/supervisor_fb_conf_windows.go
pkg/integrations/v4/supervisor_fb_conf_windows_test.go
pkg/integrations/v4/supervisor_fb_test.go
test/packaging/ansible/log-forwarder.yml
test/packaging/ansible/roles/assert-version/tasks/assert-version-Win32NT.yaml
test/packaging/ansible/roles/cleanup/tasks/files-Win32NT.yaml
test/packaging/ansible/roles/cleanup/tasks/package-Windows.yaml
test/packaging/ansible/roles/cleanup/tasks/service-Win32NT.yaml
test/packaging/ansible/roles/package-uninstall/tasks/package-Windows.yaml

This PR allows having 2 fluent bit versions (td-agent-bit 1.9 and fluent-bit 3.x) in windows. 
It embeds both fluentbits, setting the 3.x as the default one and the other one living on a -legacy folder.

Nr 91173 fluent bit 3 windows

---

test/automated/ansible/group_vars/localhost/main.yml
test/packaging/ansible/log-forwarder.yml
test/provision/terraform/caos.auto.tfvars.dist

Use caos ansible roles for tests.
Remove RHEL 7  from our canaries since docker is no longer on their yum repos https://download.docker.com/linux/rhel/7/.
They also removed the support from https://docs.docker.com/engine/install/rhel/.

Fix pipeline fluentbit legacy windows

---

cmd/newrelic-infra/newrelic-infra.go
internal/agent/status/status.go
internal/agent/status/status_test.go
internal/httpapi/httpapi.go
internal/httpapi/httpapi_test.go
pkg/backend/http/http_client.go
pkg/config/config.go

New health status check and report for the status api, it detects if the CommandApi is not returning a 200. For example if License Key is incorrect.

New health status check and report for the status api

---

cmd/newrelic-infra/dnschecks/dnschecks.go

Create a custom resolver that uses a public DNS server to check endpoint reachability but do not update the default resolver as it may affect other parts of the agent connectivity.

NR-271755 fix: use custom dialer when testing connectivity with httpTracer

---

pkg/databind/internal/secrets/command.go
pkg/databind/internal/secrets/command_test.go
pkg/databind/pkg/databind/binder.go
pkg/databind/pkg/databind/binder_test.go
pkg/databind/pkg/databind/cache.go

Scenarios handled:
If ttl is not present: use default ( DefaultTTL is used and a warning is logged to provide TTL )
If ttl is present and valid: override default ( wask as usual )
If ttl is present and invalid: throw an error ( Invalid TTL value throws error `ErrTTLInvalid` and agent does not start.

Nr 116101 - Make TTL not mandatory in secret management command

---

internal/plugins/linux/selinux.go
internal/plugins/linux/selinux_test.go

Changes in this PR
- Populating the value of versions as empty string when `semodule -l` doesn't give versions for the modules in the output
- Added test to verify the above

NR-78587 Newer versions of semodule tool do not display the SELinux modules version

---

internal/agent/agent.go
internal/agent/agent_test.go
pkg/metrics/sampler/matcher.go
pkg/metrics/sampler/matcher_test.go

This fixes [NR-334472](https://new-relic.atlassian.net/browse/NR-334472).
Due to how the logic for the `exclude_matching_metrics` option was implemented for 1.57.2, when this setting is present all samples that are not `ProcessSample`s are filtered out and not sent.
This reworks the matcher logic to cover against this and add relevant unit tests to check for the inclusion or exclusion of non-`ProcessSample` events.
[NR-334472]: https://new-relic.atlassian.net/browse/NR-334472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: `exclude_matching_metrics` is excluding non-`ProcessSample`s

---

.github/workflows/component_linux_harvest_test.yml

After Go version from the runner was bump (1.22 -> 1.23), current solution start failed with 
```
[go-get] Done.
go test ./test/harvest -tags="harvest" -v
compile: version "go1.22.8" does not match go tool version "go1.23.2"
```
I just changed the approach to use the installed go binary from the action.

chore: fix harvest test workflow

---

.github/workflows/component_linux_unit_test.yml

coverage was broken as this steps was erroring out but we still continued with failure. e.g. https://github.com/newrelic/infrastructure-agent/actions/runs/11591051096/job/32274596731
This PR fixes this issue.
https://github.com/newrelic/infrastructure-agent/actions/runs/11721033733/job/32647827916

fix coveralls workflow step failures

---

pkg/metrics/procs_windows.go
pkg/metrics/procs_windows_test.go

* Add unit test for process sample func to ensure user CPU percent and system CPU percent is between 0 and 100.

NR-322749 add test for process sample collection

---

internal/agent/status/status_test.go

Timeout was increased to `500 * time.Millisecond` allow enough time to set things up correctly.
The flakiness was due to the test expecting this specific error `http2.ErrUnexepectedResponseCode.Error()` but instead might get `"context deadline exceeded"` as the error sometimes.
By increasing timeout, there is more time for the right response to be received from the server.
Another way would be to expect that the server might timeout sometimes and check for `"context deadline exceeded."` .

Nr 337529 infra agent flaky test

---

build/embed/integrations.version

- https://github.com/newrelic/nri-prometheus/releases/tag/v2.22.0
- https://github.com/newrelic/nri-docker/releases/tag/v2.1.2
- https://github.com/newrelic/nri-flex/releases/tag/v1.16.2

Bump nri-docker, nri-flex and nri-prometheus to last versions

---

build/embed/integrations.mk

Use `fips` version of the integrations when building `fips` infra-agent.
[This](https://github.com/newrelic/infrastructure-agent/actions/runs/12386631212/job/34574795835) workflow (run) correctly downloads and includes `fips` integrations.

feat(fips): add fips integrations when building fips infra-agent

---

pkg/backend/telemetryapi/harvester.go

- Remove APIKey log
- Fix context leak, where context was not cancelled when function returned earlier
- Replace `io/ioutil` import (which was deprecated in go1.16) with `io`

fix(security): remove logging of api-key header for debug logs

---

README.md

As the CI environment is available with all the mentioned items, I think it doesn't make sense to mention these in the `README.md` anymore. Hence, removing Todos.

chore: remove todo from README.md

---

.github/workflows/repository_lastet_added_files.yml
.github/workflows/repository_lastet_added_packages.yml

GH Actions to:
* list the latest N `deb|rpm` packages in S3 Repository
* list N files created before and after date-time in S3 Repository 
Example jobs:
https://github.com/newrelic/infrastructure-agent/actions/runs/12482710904/job/34837305390
https://github.com/newrelic/infrastructure-agent/actions/runs/12482710908/job/34837305292

ci: show latest created packages in S3 Repository

---

.github/workflows/component_prerelease_testing.yml
build/build.mk
test/automated/ansible/group_vars/localhost/main.yml
test/harvest/ansible/README.md
test/harvest/ansible/roles/build-harvest-tests/tasks/main.yml
test/harvest/ansible/roles/build-harvest-tests/vars/main.yml
test/harvest/ansible/roles/run-harvest-tests/tasks/main.yml
test/harvest/ansible/roles/run-harvest-tests/vars/main.yml
test/harvest/ansible/test.yml
test/packaging/ansible/README.md
test/packaging/ansible/agent-upgrade.yml
test/packaging/ansible/installation-pinned.yml
test/packaging/ansible/installation-privileged.yml
test/packaging/ansible/installation-root.yml
test/packaging/ansible/installation-unprivileged.yml
test/packaging/ansible/shutdown-and-terminate.yml
test/packaging/ansible/test.yml
test/provision/terraform/caos.auto.tfvars.dist
test/provision/terraform/inventory.tmpl

- Update harvest tests for running on FIPS hosts
- Update packaging tests for running on FIPS hosts
- https://github.com/newrelic/infrastructure-agent/actions/runs/12595375596
- https://github.com/newrelic/infrastructure-agent/actions/runs/12669438667

feat(fips): update harvest and packaging tests to run for fips packages

---

.github/workflows/repository_lastet_added_files.yml
.github/workflows/repository_lastet_added_packages.yml

Add choice to select staging or production bucket (thanks @rajrohanyadav for the suggestion :) )

ci: flow to list files/pkgs in staging bucket

---

.github/workflows/component_molecule_packaging.yml
build/goreleaser/linux/al2023_amd64.yml
build/goreleaser/linux/al2023_arm64.yml
build/goreleaser/linux/al2_amd64.yml
build/goreleaser/linux/al2_arm64.yml
build/goreleaser/linux/centos_7_amd64.yml
build/goreleaser/linux/centos_7_arm64.yml
build/goreleaser/linux/centos_8_amd64.yml
build/goreleaser/linux/centos_8_arm64.yml
build/goreleaser/linux/debian_systemd_amd64.yml
build/goreleaser/linux/debian_systemd_arm64.yml
build/goreleaser/linux/debian_upstart_amd64.yml
build/goreleaser/linux/rhel_9_amd64.yml
build/goreleaser/linux/rhel_9_arm64.yml
build/goreleaser/linux/sles_125_amd64.yml
build/goreleaser/linux/sles_125_arm64.yml
build/goreleaser/linux/sles_152_amd64.yml
build/goreleaser/linux/sles_152_arm64.yml
build/goreleaser/linux/sles_153_amd64.yml
build/goreleaser/linux/sles_153_arm64.yml
build/goreleaser/linux/sles_154_amd64.yml
build/goreleaser/linux/sles_154_arm64.yml
build/goreleaser/linux/sles_155_amd64.yml
build/goreleaser/linux/sles_155_arm64.yml
build/goreleaser/linux/sles_156_amd64.yml
build/goreleaser/linux/sles_156_arm64.yml

Add conflict metadata between newrelic-infra and newrelic-infra-fips and set the right exec path for molecule fips tests.

Goreleaser conflict fips

---

build/goreleaser/linux/al2023_amd64.yml
build/goreleaser/linux/al2023_arm64.yml
build/goreleaser/linux/al2_amd64.yml
build/goreleaser/linux/al2_arm64.yml
build/goreleaser/linux/centos_7_amd64.yml
build/goreleaser/linux/centos_7_arm64.yml
build/goreleaser/linux/centos_8_amd64.yml
build/goreleaser/linux/centos_8_arm64.yml
build/goreleaser/linux/debian_systemd_amd64.yml
build/goreleaser/linux/debian_systemd_arm64.yml
build/goreleaser/linux/debian_upstart_amd64.yml
build/goreleaser/linux/rhel_9_amd64.yml
build/goreleaser/linux/rhel_9_arm64.yml
build/goreleaser/linux/sles_125_amd64.yml
build/goreleaser/linux/sles_125_arm64.yml
build/goreleaser/linux/sles_152_amd64.yml
build/goreleaser/linux/sles_152_arm64.yml
build/goreleaser/linux/sles_153_amd64.yml
build/goreleaser/linux/sles_153_arm64.yml
build/goreleaser/linux/sles_154_amd64.yml
build/goreleaser/linux/sles_154_arm64.yml
build/goreleaser/linux/sles_155_amd64.yml
build/goreleaser/linux/sles_155_arm64.yml
build/goreleaser/linux/sles_156_amd64.yml
build/goreleaser/linux/sles_156_arm64.yml
build/release.mk

Compute the conflict name with a placeholder replaced before rendering, since the conflicts field in goreleaser is not templatable.

Compute the conflict name with a placeholder

---

build/embed/integrations.version

bump latest version of `nri-winservices`

chore(deps): bump nri-winservices latest version

---

internal/agent/agent.go
internal/agent/agent_test.go

fix(logging): don't pollute logs with event when truncating event

---

.github/workflows/recover_s3_repository.yml

Limit the S3 Recovery action to max 7 days in the past

ci: limit S3 recovery to 7 days in the past

---

.github/workflows/sync-s3-bucket.yml

This action allows us synchronizing the Staging/Testing buckets from Production S3. Inside staging, it also allows synchronizing only `preview` repository.

ci: workflow to sync staging/testing buckets from prod

---

build/ci.mk

Copying from main S3 requires having GetObjectTagging permission over the main S3. Instead, we'll copy the objects without tags.

ci: skip tags when synchronizing buckets

---

pkg/metrics/containerd_sampler.go
pkg/metrics/docker_sampler.go

* if the host doesn't have container environment, we should not raise a warning

chore(logging): move container errors to info

---

.github/workflows/component_linux_publish.yml
.github/workflows/component_windows_publish.yml
.github/workflows/prerelease_linux_on_demand.yml
.github/workflows/prerelease_windows_on_demand.yml

This PR:
* Bumps moves into using infrastructure-publish-action v1 instead of a fix tag
* Forces the `on-demand` testing releases to be under a specific folder `testing-pre-releases`
* Allows mirroring the repo for testing purposes where you want to publish more than one package to the same on demand repository

ci: use infrastructure-publish-action v1

---

pkg/integrations/legacy/runner.go
pkg/integrations/legacy/runner_test.go
pkg/integrations/legacy/utils.go
pkg/integrations/legacy/utils_test.go
pkg/integrations/v4/dm/emitter.go
pkg/integrations/v4/dm/emitter_test.go
test/core/dummy_plugin_v4.go

integrationVersion, integrationName, reportingAgent added to inventory
`custom_attributes` from infra agent config are added with prefix `labels/ `
`labels` from ohi config file are added with prefix `labels/`

More Data added to OHI Inventory

---

.github/workflows/recover_s3_repository_periodic_test_production.yml
.github/workflows/recover_s3_repository_periodic_test_staging.yml

This PR:
* fixes slack notifications for staging disaster recovery errors
* removes `--recursive` from `rm` when deleting original
* adds job for production bucket

ci: disaster recovery dry run on prod

---

internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/cmdchannel/fflag/ffhandler.go
test/infra/agent.go

This PR adds the functionality to delete the Inventory delta files if a FF is present.

feat: feature flag to clean inventory cache on start

---

.github/workflows/component_canaries.yml
.github/workflows/component_canaries_prune.yml
.github/workflows/component_canary_alerts.yml
.github/workflows/component_canary_alerts_delete.yml
.github/workflows/component_docker_packaging.yml
.github/workflows/component_docker_publish.yml
.github/workflows/component_linux_build.yml
.github/workflows/component_linux_harvest_test.yml
.github/workflows/component_linux_packaging.yml
.github/workflows/component_linux_proxy_test.yml
.github/workflows/component_linux_publish.yml
.github/workflows/component_linux_unit_test.yml
.github/workflows/component_prerelease_testing.yml
.github/workflows/component_purge_cdn.yml
.github/workflows/component_trivy.yml
.github/workflows/component_windows_publish.yml
.github/workflows/license-notice.yml
.github/workflows/prerelease_canaries.yml
.github/workflows/prerelease_linux_on_demand.yml
.github/workflows/prerelease_windows_on_demand.yml
.github/workflows/security.yml
test/harvest/rpm_test.go

This pull request is driven by the upcoming deprecation of the Ubuntu 20.04 Actions runner image. GitHub has announced the following timeline for deprecation:
- **Deprecation Start Date**: 2025-02-01
- **Full Unsupported Date**: 2025-04-15
Given these dates, it is crucial to transition to supported runner images to ensure that our CI/CD pipelines do not encounter disruptions.
- **Objective**: Update all pipelines to use the `ubuntu-latest` runner image instead of the soon-to-be deprecated `ubuntu-20.xx`.
- **Background**: By updating to `ubuntu-latest`, we align our workflows with the latest stable and supported environment that GitHub provides. 
- **Impact**: Workflows using the `ubuntu-20.04` image label should be updated to `ubuntu-latest`.

NR-403516: Move all pipelines from ubuntu-20 runners to ubuntu-latest

---

test/a2q/systemSampleTests.yml

```sh
2025-05-07 08:31:38,295 [main] DEBUG c.n.a2q.validations.core.LocalTest - Definition location file: /a2q/systemSampleTests.yml
2025-05-07 08:31:38,298 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: accountId=*******
2025-05-07 08:31:38,298 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: nrEnv=stg
2025-05-07 08:31:38,298 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: sutEnvironment=stg
2025-05-07 08:31:38,298 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: display_name_previous=a2q_rohan_agent_1.63.0
2025-05-07 08:31:38,298 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: display_name_current=a2q_rohan_agent_1.63.1
2025-05-07 08:31:38,299 …
```

test: add a2q tests for systemSample

---

test/a2q/networkSampleTests.yml

```sh
2025-05-07 09:15:50,863 [main] DEBUG c.n.a2q.validations.core.LocalTest - Definition location file: /a2q/networkSampleTests.yml
2025-05-07 09:15:50,867 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: accountId=*******
2025-05-07 09:15:50,867 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: nrEnv=stg
2025-05-07 09:15:50,867 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: sutEnvironment=stg
2025-05-07 09:15:50,867 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: display_name_previous=a2q_rohan_agent_1.63.0
2025-05-07 09:15:50,867 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable detected: display_name_current=a2q_rohan_agent_1.63.1
2025-05-07 09:15:50,868 …
```

test: add a2q tests for networkSample

---

test/a2q/storageSampleTests.yml

**Test command:**
java -jar build/libs/validations-core-2.0.28-standalone.jar  --json  definition.location.file=/Users/nravada/newrelic/infrastructure-agent/test/a2q/StorageSampleTests.yml result.newrelic.accountId=xxx result.newrelic.licenseKey=xxxx result.newrelic.env=stg definition.var.sutEnvironment=stg definition.var.display_name_previous=a2q_nar_agent_1.63.0 definition.var.display_name_current=a2q_nar_agent_1.63.1 definition.var.accountId=xxx definition.secret.apiKey=xxxx definition.var.nrEnv=stg
**Test results:**
2025-05-08 18:07:51,634 [main] DEBUG c.n.a2q.validations.core.LocalTest - Definition location file: /Users/nravada/newrelic/infrastructure-agent/test/a2q/StorageSampleTests.yml
2025-05-08 18:07:51,636 [main] DEBUG c.n.a2q.validations.core.LocalTest - Dynamic variable …

test: add a2q tests for storageSample

---

.github/workflows/component_windows_packaging.yml
.github/workflows/prerelease_windows.yml
.github/workflows/prerelease_windows_on_demand.yml

- Update github runner for windows due to windows-2019 deprecated on 2025-06-30

fix: GH windows runner version
